import { LANGUAGES,detectLanguage,normalizeLanguage } from '../../shared/languages.js';

export const LOCALE_KEYS=Object.freeze(['hero_eyebrow','hero_subtitle','label_song','btn_find','try_label','loading_initial','loading_shared','search_meta','vibe_report','article_meta','dir_label','release_label','original_title_label','link_imdb','link_letterboxd','link_tiktok','song_card_label','btn_new_search','error_title','error_message','btn_try_again','hall_of_fame','how_it_works','about','hall_of_fame_title','hall_subtitle','how_it_works_title','step1_title','step1_text','step2_title','step2_text','step3_title','step3_text','step4_title','step4_text','about_title','about_p1','about_p2','about_p3','about_p4','add_song','remove_song','suggestions','preview','lyrics_required','lyrics_instruction','continue','cancel']);
const locale=(values)=>{if(values.length!==LOCALE_KEYS.length)throw new Error(`Incomplete locale: ${values.length}/${LOCALE_KEYS.length}`);return Object.freeze(Object.fromEntries(LOCALE_KEYS.map((key,index)=>[key,values[index]])));};

const baseTranslations=Object.freeze({
en:locale(['<span class="red-line"></span> THE CINEMA WAS ALWAYS INSIDE THE MUSIC','<em>Every song already has a film.</em> <strong>We find it.</strong>','SONG TITLE','FIND MY MOVIE →','TRY:','Listening to the atmosphere...','Loading shared vibe...','detected vibe:','VIBE REPORT','CURATOR: MOOVIBE SYSTEM <span id="res-year"></span>','DIR:','RELEASE:','ORIGINAL TITLE:','IMDb','Letterboxd','TikTok','THE SONG','← NEW SEARCH','SOMETHING WENT WRONG','We could not find that vibe. Please try again.','← TRY AGAIN','HALL OF FAME','HOW IT WORKS','ABOUT','HALL OF FAME','The greatest music-to-film matches discovered.','HOW IT WORKS','INGEST: lyrics + context','We obtain and persist the lyrics for every selected song. Lyrics are required; context is complementary.','IDENTIFY: cover + preview','Strong title, artist, album and duration matching prevents media from a different track.','MATCH: hybrid retrieval','Vectorize and numeric D1 retrieval create a diverse slate from the film catalog.','CURATE + share','Gemini chooses only from the finalist slate and explains the lyrical connection.','ABOUT',"This project was created by a film lover — without any claim to being a critic or 'cinephile' — who is also obsessed with music and soundtracks. And it was made for people who feel the same.","You know when a song makes you feel so much — like the melancholic grandeur of Harry Styles' Sign of the Times — that you wish it could last much longer? Three minutes are rarely enough to process everything a track can convey. I always wanted to extend that feeling. Since a song can't hug you for two hours straight, a movie can.","Moovibe was born from this desire: to create a bridge that automatically finds the perfect film that carries exactly the same aura, the same color, and the same vibe of your favorite song.","If this experience made you feel something cool, found an amazing film for your night, or simply liked the idea, consider following me on social media or supporting the project somehow. And if you're a developer, the source code is open waiting for you on my GitHub.",'Add another song','Remove song','Music suggestions','PREVIEW','We could not find the lyrics for this song.','To continue, paste the lyrics below.','Continue','Cancel']),
'pt-BR':locale(['<span class="red-line"></span> O CINEMA SEMPRE ESTEVE DENTRO DA MÚSICA','<em>Cada música já tem um filme.</em> <strong>Nós encontramos.</strong>','TÍTULO DA MÚSICA','ENCONTRAR MEU FILME →','TENTE:','Escutando a atmosfera...','Carregando vibe compartilhada...','vibe detectada:','RELATÓRIO DE VIBE','CURADOR: SISTEMA MOOVIBE <span id="res-year"></span>','DIR:','LANÇAMENTO:','TÍTULO ORIGINAL:','IMDb','Letterboxd','TikTok','A MÚSICA','← NOVA BUSCA','ALGO DEU ERRADO','Não foi possível encontrar essa vibe. Tente novamente.','← TENTAR NOVAMENTE','HALL DA FAMA','COMO FUNCIONA','SOBRE','HALL DA FAMA','As maiores conexões entre música e cinema já descobertas.','COMO FUNCIONA','INGESTÃO: letra + contexto','Buscamos e guardamos a letra de cada música. A letra é obrigatória; o contexto é complementar.','IDENTIDADE: capa + prévia','Uma validação forte de título, artista, álbum e duração impede mídia de outra faixa.','MATCH: busca híbrida','Vectorize e o canal numérico do D1 criam uma seleção diversa do catálogo.','CURADORIA + compartilhar','O Gemini escolhe apenas entre os finalistas e explica a conexão lírica.','SOBRE',"Este projeto foi criado por um amante de filmes — sem a pretensão de ser crítico ou 'cinéfilo' — que também é obcecado por música e trilhas sonoras. E ele foi feito para pessoas que sentem o mesmo.",'Sabe quando uma música te faz sentir tanta coisa — como a grandiosidade melancólica de Sign of the Times do Harry Styles — que você queria que ela durasse muito mais? Três minutos raramente são suficientes para processar tudo o que uma faixa pode transmitir. Eu sempre quis estender essa sensação. Já que uma música não pode te abraçar por duas horas seguidas, um filme pode.','O Moovibe nasceu dessa minha vontade: criar uma ponte que encontre automaticamente o filme perfeito que carrega exatamente a mesma aura, a mesma cor e a mesma vibe da sua música favorita.','Se essa experiência fez você sentir algo legal, encontrou um filme incrível para a sua noite ou simplesmente curtiu a ideia, considere me seguir nas redes sociais ou apoiar o projeto de alguma forma. E se você for desenvolvedor, o código-fonte está aberto no meu GitHub te esperando.','Adicionar outra música','Remover música','Sugestões de música','PRÉVIA','Não encontramos a letra desta música.','Para continuar, cole a letra abaixo.','Continuar','Cancelar']),
'zh-CN':locale(['<span class="red-line"></span> 电影一直藏在音乐之中','<em>每首歌都有一部属于它的电影。</em> <strong>我们来找到它。</strong>','歌曲名称','寻找我的电影 →','试试：','正在聆听氛围…','正在加载分享的氛围…','检测到的氛围：','氛围报告','策展：MOOVIBE 系统 <span id="res-year"></span>','导演：','上映：','原片名：','IMDb','Letterboxd','TikTok','歌曲','← 重新搜索','出现问题','无法找到这种氛围，请重试。','← 再试一次','名人堂','工作原理','关于','名人堂','已发现的精彩音乐与电影匹配。','工作原理','采集：歌词与背景','我们会获取并保存每首所选歌曲的歌词。歌词是必需的，背景信息作为补充。','识别：封面与试听','通过严格匹配歌名、艺人、专辑和时长，避免展示其他歌曲的媒体。','匹配：混合检索','Vectorize 与 D1 数值检索从电影目录中生成多样化候选集。','策展与分享','Gemini 只从最终候选中选择，并解释与歌词的联系。','关于','Moovibe 由一位热爱电影与音乐的人创作，献给同样深切感受二者的人。','一首歌可以容纳完整的电影世界，Moovibe 让这种感受延续一整部电影。','它在音乐与电影的气息、色彩和情感之间搭起桥梁。','这是一个用心制作的开源项目。','添加另一首歌','移除歌曲','歌曲建议','试听','我们没有找到这首歌的歌词。','请粘贴歌词以继续。','继续','取消']),
ru:locale(['<span class="red-line"></span> КИНО ВСЕГДА БЫЛО ВНУТРИ МУЗЫКИ','<em>У каждой песни уже есть свой фильм.</em> <strong>Мы его найдём.</strong>','НАЗВАНИЕ ПЕСНИ','НАЙТИ МОЙ ФИЛЬМ →','ПОПРОБУЙТЕ:','Слушаем атмосферу…','Загружаем общую рекомендацию…','найденная атмосфера:','ОТЧЁТ ОБ АТМОСФЕРЕ','КУРАТОР: СИСТЕМА MOOVIBE <span id="res-year"></span>','РЕЖ.:','ГОД ВЫХОДА:','ОРИГИНАЛЬНОЕ НАЗВАНИЕ:','IMDb','Letterboxd','TikTok','ПЕСНЯ','← НОВЫЙ ПОИСК','ЧТО-ТО ПОШЛО НЕ ТАК','Не удалось найти эту атмосферу. Попробуйте ещё раз.','← ПОПРОБОВАТЬ СНОВА','ЗАЛ СЛАВЫ','КАК ЭТО РАБОТАЕТ','О ПРОЕКТЕ','ЗАЛ СЛАВЫ','Лучшие найденные сочетания музыки и кино.','КАК ЭТО РАБОТАЕТ','СБОР: текст и контекст','Мы находим и сохраняем текст каждой выбранной песни. Текст обязателен, контекст дополняет анализ.','ИДЕНТИФИКАЦИЯ: обложка и фрагмент','Точная сверка названия, исполнителя, альбома и длительности исключает чужие записи.','ПОИСК: гибридная модель','Vectorize и числовой поиск D1 формируют разнообразный список из каталога фильмов.','КУРАТОРСТВО И ОБМЕН','Gemini выбирает только среди финалистов и объясняет связь с текстом.','О ПРОЕКТЕ','Moovibe создан любителем кино и музыки для тех, кто так же глубоко чувствует и то и другое.','В одной песне может жить целый мир кино. Moovibe продлевает это чувство на весь фильм.','Проект соединяет атмосферу, цвет и эмоции музыки и кинематографа.','Это открытый проект, созданный с заботой.','Добавить ещё песню','Удалить песню','Подсказки песен','ФРАГМЕНТ','Текст этой песни не найден.','Вставьте текст песни, чтобы продолжить.','Продолжить','Отмена']),
es:locale(['<span class="red-line"></span> EL CINE SIEMPRE ESTUVO DENTRO DE LA MÚSICA','<em>Cada canción ya tiene una película.</em> <strong>Nosotros la encontramos.</strong>','TÍTULO DE LA CANCIÓN','ENCONTRAR MI PELÍCULA →','PRUEBA:','Escuchando la atmósfera...','Cargando la vibra compartida...','vibra detectada:','INFORME DE VIBRA','CURADOR: SISTEMA MOOVIBE <span id="res-year"></span>','DIR.:','ESTRENO:','TÍTULO ORIGINAL:','IMDb','Letterboxd','TikTok','LA CANCIÓN','← NUEVA BÚSQUEDA','ALGO SALIÓ MAL','No pudimos encontrar esa vibra. Inténtalo de nuevo.','← VOLVER A INTENTAR','SALÓN DE LA FAMA','CÓMO FUNCIONA','ACERCA DE','SALÓN DE LA FAMA','Las mejores conexiones descubiertas entre música y cine.','CÓMO FUNCIONA','INGESTA: letra + contexto','Obtenemos y guardamos la letra de cada canción elegida. La letra es obligatoria y el contexto es complementario.','IDENTIDAD: portada + adelanto','La coincidencia estricta de título, artista, álbum y duración evita mostrar otra canción.','MATCH: búsqueda híbrida','Vectorize y la búsqueda numérica de D1 crean una selección diversa del catálogo.','CURADURÍA + compartir','Gemini elige solo entre los finalistas y explica la conexión con la letra.','ACERCA DE','Moovibe fue creado por un amante del cine y la música para quienes sienten ambos con intensidad.','Una canción puede contener todo un mundo cinematográfico. Moovibe prolonga esa sensación durante una película.','Construye un puente entre el aura, el color y la emoción de la música y el cine.','Es un proyecto de código abierto hecho con dedicación.','Añadir otra canción','Quitar canción','Sugerencias de canciones','ADELANTO','No encontramos la letra de esta canción.','Para continuar, pega la letra.','Continuar','Cancelar']),
de:locale(['<span class="red-line"></span> DAS KINO WAR SCHON IMMER IN DER MUSIK','<em>Jeder Song hat bereits einen Film.</em> <strong>Wir finden ihn.</strong>','SONGTITEL','MEINEN FILM FINDEN →','PROBIERE:','Wir hören die Atmosphäre…','Geteilte Stimmung wird geladen…','erkannte Stimmung:','STIMMUNGSBERICHT','KURATOR: MOOVIBE-SYSTEM <span id="res-year"></span>','REGIE:','ERSCHIENEN:','ORIGINALTITEL:','IMDb','Letterboxd','TikTok','DER SONG','← NEUE SUCHE','ETWAS IST SCHIEFGELAUFEN','Diese Stimmung konnte nicht gefunden werden. Bitte versuche es erneut.','← ERNEUT VERSUCHEN','RUHMESHALLE','SO FUNKTIONIERT ES','ÜBER UNS','RUHMESHALLE','Die besten entdeckten Verbindungen zwischen Musik und Film.','SO FUNKTIONIERT ES','ERFASSEN: Text + Kontext','Wir beziehen und speichern den Text jedes gewählten Songs. Der Songtext ist erforderlich, Kontext ergänzt die Analyse.','ERKENNEN: Cover + Hörprobe','Der strenge Abgleich von Titel, Interpret, Album und Dauer verhindert Medien eines anderen Songs.','ABGLEICH: hybride Suche','Vectorize und die numerische D1-Suche erzeugen eine vielfältige Auswahl aus dem Filmkatalog.','KURATIEREN + teilen','Gemini wählt nur aus den Finalisten und erklärt die Verbindung zum Songtext.','ÜBER UNS','Moovibe wurde von einem Film- und Musikliebhaber für Menschen geschaffen, die beides intensiv empfinden.','Ein Song kann eine ganze filmische Welt enthalten. Moovibe lässt dieses Gefühl einen ganzen Film lang weiterleben.','Es schlägt eine Brücke zwischen Aura, Farbe und Emotion von Musik und Kino.','Das Projekt ist quelloffen und mit Sorgfalt gemacht.','Weiteren Song hinzufügen','Song entfernen','Songvorschläge','HÖRPROBE','Wir konnten den Songtext nicht finden.','Füge den Songtext ein, um fortzufahren.','Weiter','Abbrechen']),
fr:locale(['<span class="red-line"></span> LE CINÉMA A TOUJOURS ÉTÉ DANS LA MUSIQUE','<em>Chaque chanson a déjà son film.</em> <strong>Nous le trouvons.</strong>','TITRE DE LA CHANSON','TROUVER MON FILM →','ESSAYEZ :','À l’écoute de l’atmosphère…','Chargement de la vibe partagée…','vibe détectée :','RAPPORT DE VIBE','CURATEUR : SYSTÈME MOOVIBE <span id="res-year"></span>','RÉAL. :','SORTIE :','TITRE ORIGINAL :','IMDb','Letterboxd','TikTok','LA CHANSON','← NOUVELLE RECHERCHE','UN PROBLÈME EST SURVENU','Impossible de trouver cette vibe. Réessayez.','← RÉESSAYER','PANTHÉON','COMMENT ÇA MARCHE','À PROPOS','PANTHÉON','Les plus belles correspondances découvertes entre musique et cinéma.','COMMENT ÇA MARCHE','INGESTION : paroles + contexte','Nous obtenons et conservons les paroles de chaque chanson choisie. Les paroles sont obligatoires, le contexte est complémentaire.','IDENTITÉ : pochette + extrait','Une vérification stricte du titre, de l’artiste, de l’album et de la durée évite les médias d’un autre morceau.','MATCH : recherche hybride','Vectorize et la recherche numérique D1 créent une sélection variée depuis le catalogue.','SÉLECTION + partage','Gemini choisit uniquement parmi les finalistes et explique le lien avec les paroles.','À PROPOS','Moovibe a été créé par un passionné de cinéma et de musique pour celles et ceux qui ressentent profondément les deux.','Une chanson peut contenir tout un monde de cinéma. Moovibe prolonge cette sensation le temps d’un film.','Il crée un pont entre l’aura, la couleur et l’émotion de la musique et du cinéma.','Le projet est open source et réalisé avec soin.','Ajouter une chanson','Retirer la chanson','Suggestions de chansons','EXTRAIT','Nous n’avons pas trouvé les paroles de cette chanson.','Collez les paroles pour continuer.','Continuer','Annuler']),
ja:locale(['<span class="red-line"></span> 映画はいつも音楽の中にあった','<em>どの曲にも、すでに映画がある。</em> <strong>私たちが見つけます。</strong>','曲名','映画を見つける →','試してみる：','雰囲気を聴き取っています…','共有されたムードを読み込み中…','検出されたムード：','ムードレポート','キュレーター：MOOVIBE システム <span id="res-year"></span>','監督：','公開：','原題：','IMDb','Letterboxd','TikTok','楽曲','← 新しい検索','問題が発生しました','このムードを見つけられませんでした。もう一度お試しください。','← もう一度試す','殿堂','仕組み','概要','殿堂','これまでに見つかった音楽と映画の素晴らしい組み合わせ。','仕組み','取得：歌詞＋背景','選んだ各曲の歌詞を取得して保存します。歌詞は必須で、背景情報は分析を補います。','識別：カバー＋試聴','曲名、アーティスト、アルバム、長さを厳密に照合し、別の曲のメディアを防ぎます。','照合：ハイブリッド検索','Vectorize と D1 の数値検索で、映画カタログから多様な候補を作ります。','選定＋共有','Gemini は最終候補だけから選び、歌詞とのつながりを説明します。','概要','Moovibe は映画と音楽を愛する人が、その両方を深く感じる人のために作りました。','一曲の中には映画の世界全体が宿ります。Moovibe はその感覚を映画一本分まで延ばします。','音楽と映画の空気、色、感情をつなぐ架け橋です。','心を込めて作られたオープンソースプロジェクトです。','別の曲を追加','曲を削除','曲の候補','試聴','この曲の歌詞が見つかりませんでした。','続けるには歌詞を貼り付けてください。','続ける','キャンセル'])
});

const PERSONAL_ABOUT=Object.freeze({
en:["This project was created by a film lover — without any claim to being a critic or 'cinephile' — who is also obsessed with music and soundtracks. And it was made for people who feel the same.","You know when a song makes you feel so much — like the melancholic grandeur of Harry Styles' Sign of the Times — that you wish it could last much longer? Three minutes are rarely enough to process everything a track can convey. I always wanted to extend that feeling. Since a song can't hug you for two hours straight, a movie can.","Moovibe was born from this desire: to create a bridge that automatically finds the perfect film that carries exactly the same aura, the same color, and the same vibe of your favorite song.","If this experience made you feel something cool, found an amazing film for your night, or simply liked the idea, consider following me on social media or supporting the project somehow. And if you're a developer, the source code is open waiting for you on my GitHub."],
'pt-BR':["Este projeto foi criado por um amante de filmes — sem a pretensão de ser crítico ou 'cinéfilo' — que também é obcecado por música e trilhas sonoras. E ele foi feito para pessoas que sentem o mesmo.",'Sabe quando uma música te faz sentir tanta coisa — como a grandiosidade melancólica de Sign of the Times do Harry Styles — que você queria que ela durasse muito mais? Três minutos raramente são suficientes para processar tudo o que uma faixa pode transmitir. Eu sempre quis estender essa sensação. Já que uma música não pode te abraçar por duas horas seguidas, um filme pode.','O Moovibe nasceu dessa minha vontade: criar uma ponte que encontre automaticamente o filme perfeito que carrega exatamente a mesma aura, a mesma cor e a mesma vibe da sua música favorita.','Se essa experiência fez você sentir algo legal, encontrou um filme incrível para a sua noite ou simplesmente curtiu a ideia, considere me seguir nas redes sociais ou apoiar o projeto de alguma forma. E se você for desenvolvedor, o código-fonte está aberto no meu GitHub te esperando.'],
'zh-CN':['这个项目由一位电影爱好者创作——无意自称影评人或“资深影迷”——同时也痴迷音乐和电影原声。它献给有同样感受的人。','你是否也曾被一首歌触动得如此强烈——比如 Harry Styles 的《Sign of the Times》那种忧郁而恢宏的感觉——希望它能持续得更久？三分钟很少足以消化一首歌所传达的一切。我一直想延长这种感受。既然一首歌无法连续拥抱你两个小时，一部电影可以。','Moovibe 正是源于这个愿望：搭起一座桥梁，自动找到那部拥有与你最爱的歌曲完全相同的气息、色彩与氛围的电影。','如果这段体验让你有所触动、为你的夜晚找到了一部精彩电影，或只是喜欢这个想法，欢迎在社交媒体上关注我或以某种方式支持这个项目。如果你是开发者，源代码也正在 GitHub 上等着你。'],
ru:['Этот проект создал любитель кино — без претензий на звание критика или «синефила», — который также одержим музыкой и саундтреками. И он сделан для людей, чувствующих то же самое.','Знаете это чувство, когда песня вызывает столько эмоций — как меланхоличное величие Sign of the Times Гарри Стайлса, — что хочется, чтобы она длилась гораздо дольше? Трёх минут редко хватает, чтобы осмыслить всё, что способна передать композиция. Мне всегда хотелось продлить это чувство. Песня не может обнимать вас два часа подряд, а фильм может.','Из этого желания и родился Moovibe: создать мост, который автоматически находит идеальный фильм с той же аурой, тем же цветом и тем же настроением, что и ваша любимая песня.','Если этот опыт вас тронул, помог найти замечательный фильм на вечер или вам просто понравилась идея, подпишитесь на меня в социальных сетях или поддержите проект. А если вы разработчик, открытый исходный код ждёт вас на GitHub.'],
es:['Este proyecto fue creado por un amante del cine —sin pretender ser crítico ni «cinéfilo»— que también está obsesionado con la música y las bandas sonoras. Y fue hecho para quienes sienten lo mismo.','¿Conoces esa sensación cuando una canción te hace sentir tanto —como la grandeza melancólica de Sign of the Times de Harry Styles— que quisieras que durara mucho más? Tres minutos rara vez bastan para procesar todo lo que una canción puede transmitir. Siempre quise prolongar esa sensación. Ya que una canción no puede abrazarte durante dos horas seguidas, una película sí.','Moovibe nació de ese deseo: crear un puente que encuentre automáticamente la película perfecta con exactamente la misma aura, el mismo color y la misma vibra que tu canción favorita.','Si esta experiencia te hizo sentir algo, te ayudó a encontrar una película increíble para la noche o simplemente te gustó la idea, puedes seguirme en redes sociales o apoyar el proyecto. Y si eres desarrollador, el código fuente abierto te espera en GitHub.'],
de:['Dieses Projekt wurde von einem Filmliebhaber geschaffen — ohne den Anspruch, Kritiker oder „Cineast“ zu sein —, der ebenso von Musik und Soundtracks besessen ist. Es ist für Menschen gemacht, die genauso empfinden.','Kennst du das, wenn ein Song so viel in dir auslöst — wie die melancholische Größe von Harry Styles’ Sign of the Times —, dass du dir wünschst, er würde viel länger dauern? Drei Minuten reichen selten aus, um alles zu verarbeiten, was ein Song vermitteln kann. Ich wollte dieses Gefühl schon immer verlängern. Ein Song kann dich nicht zwei Stunden lang umarmen, ein Film schon.','Aus diesem Wunsch entstand Moovibe: eine Brücke zu bauen, die automatisch den perfekten Film mit genau derselben Aura, derselben Farbe und derselben Stimmung wie dein Lieblingssong findet.','Wenn dieses Erlebnis etwas in dir ausgelöst, dir einen großartigen Film für den Abend gezeigt oder dir die Idee einfach gefallen hat, folge mir gern in den sozialen Medien oder unterstütze das Projekt. Und wenn du entwickelst, wartet der offene Quellcode auf GitHub auf dich.'],
fr:['Ce projet a été créé par un amoureux du cinéma — sans prétendre être critique ou « cinéphile » — également passionné de musique et de bandes originales. Il s’adresse à celles et ceux qui ressentent la même chose.','Vous connaissez ce moment où une chanson vous fait ressentir tant de choses — comme la grandeur mélancolique de Sign of the Times de Harry Styles — que vous aimeriez qu’elle dure beaucoup plus longtemps ? Trois minutes suffisent rarement pour accueillir tout ce qu’un morceau peut transmettre. J’ai toujours voulu prolonger cette sensation. Puisqu’une chanson ne peut pas vous étreindre pendant deux heures, un film le peut.','Moovibe est né de ce désir : créer un pont capable de trouver automatiquement le film parfait, porteur de la même aura, de la même couleur et de la même vibe que votre chanson préférée.','Si cette expérience vous a touché, vous a fait découvrir un film formidable pour votre soirée ou si l’idée vous a simplement plu, vous pouvez me suivre sur les réseaux sociaux ou soutenir le projet. Et si vous développez, le code source ouvert vous attend sur GitHub.'],
ja:['このプロジェクトは、批評家や「シネフィル」を名乗るつもりはないものの、映画を愛し、音楽とサウンドトラックにも夢中な一人の人間が作りました。同じように感じる人たちのためのプロジェクトです。','曲に心を大きく動かされ、もっと長く続いてほしいと思ったことはありませんか。たとえば、Harry Styles の Sign of the Times が持つメランコリックな壮大さのように。曲が伝えるすべてを受け止めるには、三分では足りないことがほとんどです。私はずっと、その感覚を引き延ばしたいと思っていました。曲が二時間ずっとあなたを抱きしめることはできなくても、映画ならできます。','Moovibe はその思いから生まれました。お気に入りの曲とまったく同じ空気、色、雰囲気を持つ完璧な映画を自動で見つける橋を作りたかったのです。','この体験が何かを感じさせてくれた、素敵な夜のための映画に出会えた、あるいは単純にアイデアを気に入ってくれたなら、SNS をフォローしたり、何らかの形でプロジェクトを応援してもらえたら嬉しいです。開発者の方には、GitHub でオープンソースのコードも待っています。']
});

export const translations=Object.freeze(Object.fromEntries(Object.entries(baseTranslations).map(([code,dictionary])=>{const [about_p1,about_p2,about_p3,about_p4]=PERSONAL_ABOUT[code];return [code,Object.freeze({...dictionary,about_p1,about_p2,about_p3,about_p4})];})));

export {LANGUAGES,detectLanguage,normalizeLanguage};
export const BETA_COPY=Object.freeze({
en:['PUBLIC BETA<br>CATALOG IN PROGRESS','Moovibe is in beta. The catalog is still growing, and some songs may require you to provide the lyrics before the analysis can continue.'],
'pt-BR':['BETA PÚBLICA<br>CATÁLOGO EM CONSTRUÇÃO','O Moovibe está em beta. O catálogo ainda está crescendo e algumas músicas podem exigir que você forneça a letra para continuar a análise.'],
'zh-CN':['公开测试<br>片库持续扩充中','Moovibe 目前处于测试阶段。片库仍在扩充，部分歌曲可能需要您提供歌词才能继续分析。'],ru:['ПУБЛИЧНАЯ БЕТА<br>КАТАЛОГ ПОПОЛНЯЕТСЯ','Moovibe находится в бета-версии. Каталог продолжает расти, и для анализа некоторых песен может потребоваться текст.'],es:['BETA PÚBLICA<br>CATÁLOGO EN PROGRESO','Moovibe está en beta. El catálogo sigue creciendo y algunas canciones pueden requerir que proporciones la letra para continuar el análisis.'],de:['ÖFFENTLICHE BETA<br>KATALOG IM AUFBAU','Moovibe befindet sich in der Beta-Phase. Der Katalog wächst noch; bei manchen Songs musst du den Text angeben, damit die Analyse fortgesetzt werden kann.'],fr:['BÊTA PUBLIQUE<br>CATALOGUE EN COURS','Moovibe est en bêta. Le catalogue continue de s’enrichir et certaines chansons peuvent nécessiter leurs paroles pour poursuivre l’analyse.'],ja:['公開ベータ<br>カタログ拡充中','Moovibe はベータ版です。カタログは拡充中のため、分析を続けるには歌詞の入力が必要な曲もあります。']});
export function localeKeysMatch(locales=translations){const expected=Object.keys(locales.en).sort().join('|');return Object.values(locales).every(item=>Object.keys(item).sort().join('|')===expected);}

export const PAGE_METADATA=Object.freeze({
en:{home:['Moovibe — Find the film with your song’s vibe','Type a song and discover the film with the same atmosphere, color and emotion.'],about:['Moovibe — About','Meet Moovibe, the project connecting music and film through atmosphere, color and emotion.'],how:['Moovibe — How it works','See how Moovibe finds a film with the same vibe as your favorite song.'],hall:['Moovibe — Hall of Fame','The greatest music-to-film connections discovered by Moovibe.']},
'pt-BR':{home:['Moovibe — Descubra o filme com a vibe da sua música','Digite uma música e descubra o filme com a mesma atmosfera, cor e emoção.'],about:['Moovibe — Sobre','Conheça o projeto que conecta músicas e filmes pela atmosfera, cor e emoção.'],how:['Moovibe — Como funciona','Entenda como o Moovibe encontra o filme com a vibe da sua música favorita.'],hall:['Moovibe — Hall da Fama','As maiores conexões entre música e cinema descobertas pelo Moovibe.']},
'zh-CN':{home:['Moovibe — 找到与歌曲氛围相同的电影','输入一首歌，发现拥有相同氛围、色彩与情感的电影。'],about:['Moovibe — 关于','了解以氛围、色彩和情感连接音乐与电影的 Moovibe。'],how:['Moovibe — 工作原理','了解 Moovibe 如何为你喜爱的歌曲找到同样氛围的电影。'],hall:['Moovibe — 名人堂','Moovibe 发现的精彩音乐与电影连接。']},
ru:{home:['Moovibe — Найдите фильм с атмосферой вашей песни','Введите песню и найдите фильм с теми же атмосферой, цветом и эмоцией.'],about:['Moovibe — О проекте','Узнайте о Moovibe — проекте, соединяющем музыку и кино.'],how:['Moovibe — Как это работает','Узнайте, как Moovibe находит фильм с настроением любимой песни.'],hall:['Moovibe — Зал славы','Лучшие связи музыки и кино, найденные Moovibe.']},
es:{home:['Moovibe — Descubre la película con la vibra de tu canción','Escribe una canción y descubre la película con la misma atmósfera, color y emoción.'],about:['Moovibe — Acerca de','Conoce el proyecto que conecta música y cine mediante atmósfera, color y emoción.'],how:['Moovibe — Cómo funciona','Descubre cómo Moovibe encuentra una película con la vibra de tu canción favorita.'],hall:['Moovibe — Salón de la fama','Las mejores conexiones entre música y cine descubiertas por Moovibe.']},
de:{home:['Moovibe — Finde den Film zur Stimmung deines Songs','Gib einen Song ein und entdecke den Film mit derselben Atmosphäre, Farbe und Emotion.'],about:['Moovibe — Über uns','Lerne das Projekt kennen, das Musik und Film durch Atmosphäre und Emotion verbindet.'],how:['Moovibe — So funktioniert es','Erfahre, wie Moovibe einen Film zur Stimmung deines Lieblingssongs findet.'],hall:['Moovibe — Ruhmeshalle','Die besten von Moovibe entdeckten Verbindungen zwischen Musik und Film.']},
fr:{home:['Moovibe — Trouvez le film qui partage la vibe de votre chanson','Saisissez une chanson et découvrez le film avec la même atmosphère, couleur et émotion.'],about:['Moovibe — À propos','Découvrez le projet qui relie musique et cinéma par l’atmosphère et l’émotion.'],how:['Moovibe — Comment ça marche','Découvrez comment Moovibe trouve un film avec la vibe de votre chanson préférée.'],hall:['Moovibe — Panthéon','Les plus belles connexions entre musique et cinéma découvertes par Moovibe.']},
ja:{home:['Moovibe — 曲の雰囲気に合う映画を見つける','曲を入力して、同じ空気、色、感情を持つ映画を見つけましょう。'],about:['Moovibe — 概要','音楽と映画を空気、色、感情で結ぶ Moovibe を紹介します。'],how:['Moovibe — 仕組み','Moovibe が好きな曲と同じ雰囲気の映画を見つける仕組みです。'],hall:['Moovibe — 殿堂','Moovibe が見つけた音楽と映画の素晴らしいつながり。']}
});

export const IDENTITY_COPY=Object.freeze({
en:['Type a song or paste a Spotify link','WHICH SONG DID YOU MEAN?','Choose the exact recording before we analyze it.','None of these','This Spotify link cannot be verified now. Search by song name.','This Spotify link is not a song.'],
'pt-BR':['Digite uma música ou cole um link do Spotify','QUAL MÚSICA VOCÊ QUIS DIZER?','Escolha a gravação exata antes da análise.','Nenhuma dessas','Não foi possível verificar esse link agora. Pesquise pelo nome da música.','Esse link do Spotify não é de uma música.'],
'zh-CN':['输入歌曲或粘贴 Spotify 链接','你指的是哪首歌？','分析前请选择准确的录音版本。','都不是','目前无法验证此链接，请按歌曲名称搜索。','这个 Spotify 链接不是歌曲。'],
ru:['Введите песню или вставьте ссылку Spotify','КАКУЮ ПЕСНЮ ВЫ ИМЕЛИ В ВИДУ?','Перед анализом выберите точную запись.','Ни одну','Сейчас не удалось проверить ссылку. Найдите песню по названию.','Эта ссылка Spotify ведёт не на песню.'],
es:['Escribe una canción o pega un enlace de Spotify','¿QUÉ CANCIÓN QUISISTE DECIR?','Elige la grabación exacta antes del análisis.','Ninguna','No se pudo verificar el enlace. Busca por el nombre de la canción.','Este enlace de Spotify no corresponde a una canción.'],
de:['Song eingeben oder Spotify-Link einfügen','WELCHEN SONG MEINST DU?','Wähle vor der Analyse die genaue Aufnahme.','Keinen davon','Der Link kann gerade nicht geprüft werden. Suche nach dem Songnamen.','Dieser Spotify-Link führt nicht zu einem Song.'],
fr:['Saisissez une chanson ou collez un lien Spotify','QUELLE CHANSON VOULEZ-VOUS DIRE ?','Choisissez l’enregistrement exact avant l’analyse.','Aucune','Impossible de vérifier ce lien. Recherchez avec le titre de la chanson.','Ce lien Spotify ne correspond pas à une chanson.'],
ja:['曲名を入力するか Spotify リンクを貼り付ける','どの曲ですか？','分析前に正確な音源を選んでください。','どれでもない','現在このリンクを確認できません。曲名で検索してください。','この Spotify リンクは曲ではありません。']
});

export const TRACK_SELECTION_COPY=Object.freeze({
en:['CHANGE','Confirmed song','Choose a song from the suggestions.'],'pt-BR':['TROCAR','Música confirmada','Escolha uma música nas sugestões.'],'zh-CN':['更换','已确认歌曲','请从建议中选择歌曲。'],ru:['ИЗМЕНИТЬ','Песня подтверждена','Выберите песню из подсказок.'],es:['CAMBIAR','Canción confirmada','Elige una canción de las sugerencias.'],de:['ÄNDERN','Song bestätigt','Wähle einen Song aus den Vorschlägen.'],fr:['CHANGER','Chanson confirmée','Choisissez une chanson parmi les suggestions.'],ja:['変更','確認済みの曲','候補から曲を選んでください。']
});

export const AUTOCOMPLETE_COPY=Object.freeze({
en:{loading:['SEARCHING TRACKS...',''],empty:['NO TRACKS FOUND','Try title + artist.'],error:['COULD NOT SEARCH RIGHT NOW','Try again in a few seconds.']},
'pt-BR':{loading:['BUSCANDO FAIXAS...',''],empty:['NENHUMA FAIXA ENCONTRADA','Tente título + artista.'],error:['NÃO FOI POSSÍVEL BUSCAR AGORA','Tente novamente em alguns segundos.']},
'zh-CN':{loading:['正在搜索歌曲…',''],empty:['未找到歌曲','请尝试“歌名 + 艺人”。'],error:['目前无法搜索','请几秒后重试。']},
ru:{loading:['ИЩЕМ ТРЕКИ…',''],empty:['ТРЕКИ НЕ НАЙДЕНЫ','Попробуйте название + исполнитель.'],error:['СЕЙЧАС ПОИСК НЕДОСТУПЕН','Повторите попытку через несколько секунд.']},
es:{loading:['BUSCANDO CANCIONES...',''],empty:['NO SE ENCONTRARON CANCIONES','Prueba título + artista.'],error:['NO SE PUEDE BUSCAR AHORA','Inténtalo de nuevo en unos segundos.']},
de:{loading:['TITEL WERDEN GESUCHT...',''],empty:['KEINE TITEL GEFUNDEN','Versuche Titel + Interpret.'],error:['SUCHE GERADE NICHT MÖGLICH','Versuche es in einigen Sekunden erneut.']},
fr:{loading:['RECHERCHE DE TITRES...',''],empty:['AUCUN TITRE TROUVÉ','Essayez titre + artiste.'],error:['RECHERCHE IMPOSSIBLE POUR LE MOMENT','Réessayez dans quelques secondes.']},
ja:{loading:['曲を検索中…',''],empty:['曲が見つかりませんでした','曲名 + アーティスト名をお試しください。'],error:['現在検索できません','数秒後にもう一度お試しください。']}
});

export const RESULT_COPY=Object.freeze({
en:['VIEW LYRICS','HIDE LYRICS','LYRICS','SOURCE','VIEW AT SOURCE ↗','OTHER SUGGESTIONS','OPEN IN SPOTIFY ↗','ALBUM'],
'pt-BR':['VER LETRA','OCULTAR LETRA','LETRA','FONTE','VER NA FONTE ↗','OUTRAS SUGESTÕES','ABRIR NO SPOTIFY ↗','ÁLBUM'],
'zh-CN':['查看歌词','隐藏歌词','歌词','来源','前往来源 ↗','其他推荐','在 SPOTIFY 中打开 ↗','专辑'],ru:['ПОКАЗАТЬ ТЕКСТ','СКРЫТЬ ТЕКСТ','ТЕКСТ ПЕСНИ','ИСТОЧНИК','ОТКРЫТЬ ИСТОЧНИК ↗','ДРУГИЕ ВАРИАНТЫ','ОТКРЫТЬ В SPOTIFY ↗','АЛЬБОМ'],es:['VER LETRA','OCULTAR LETRA','LETRA','FUENTE','VER EN LA FUENTE ↗','OTRAS SUGERENCIAS','ABRIR EN SPOTIFY ↗','ÁLBUM'],de:['SONGTEXT ZEIGEN','SONGTEXT AUSBLENDEN','SONGTEXT','QUELLE','QUELLE ÖFFNEN ↗','WEITERE VORSCHLÄGE','IN SPOTIFY ÖFFNEN ↗','ALBUM'],fr:['VOIR LES PAROLES','MASQUER LES PAROLES','PAROLES','SOURCE','VOIR À LA SOURCE ↗','AUTRES SUGGESTIONS','OUVRIR DANS SPOTIFY ↗','ALBUM'],ja:['歌詞を見る','歌詞を隠す','歌詞','出典','出典を見る ↗','ほかの候補','SPOTIFY で開く ↗','アルバム']
});

export const LOADING_INTERACTION_COPY=Object.freeze({
en:{paused:'ANALYSIS PAUSED',not_found:'WE COULD NOT FIND THE LYRICS TO THIS SONG.',explain:'This track may be instrumental, or its lyrics may not be available.',provide:'PROVIDE LYRICS',instrumental:'THIS SONG IS INSTRUMENTAL',retry:'TRY AGAIN',waiting:'WAITING FOR YOUR RESPONSE',continue:'CONTINUE ANALYSIS',back:'BACK TO OPTIONS',cancel:'CANCEL SEARCH',provider:'WE CANNOT CHECK THE LYRICS RIGHT NOW.',insufficient:'WE DO NOT HAVE ENOUGH SOUND INFORMATION TO ANALYZE THIS TRACK.',resume:'RESUMING ANALYSIS…'},
'pt-BR':{paused:'ANÁLISE INTERROMPIDA',not_found:'NÃO ENCONTRAMOS A LETRA DESTA MÚSICA.',explain:'Esta faixa pode ser instrumental ou sua letra pode não estar disponível.',provide:'FORNECER LETRA',instrumental:'ESTA MÚSICA É INSTRUMENTAL',retry:'TENTAR NOVAMENTE',waiting:'AGUARDANDO SUA RESPOSTA',continue:'CONTINUAR ANÁLISE',back:'VOLTAR ÀS OPÇÕES',cancel:'CANCELAR BUSCA',provider:'NÃO CONSEGUIMOS CONSULTAR AS LETRAS AGORA.',insufficient:'NÃO TEMOS INFORMAÇÕES SONORAS SUFICIENTES PARA ANALISAR ESTA FAIXA.',resume:'RETOMANDO ANÁLISE…'},
'zh-CN':{paused:'分析已暂停',not_found:'未找到这首歌的歌词。',explain:'该曲目可能是纯音乐，或歌词暂不可用。',provide:'提供歌词',instrumental:'这首歌是纯音乐',retry:'重试',waiting:'等待您的选择',continue:'继续分析',back:'返回选项',cancel:'取消搜索',provider:'目前无法查询歌词。',insufficient:'声音信息不足，无法分析此曲目。',resume:'正在继续分析…'},
ru:{paused:'АНАЛИЗ ПРИОСТАНОВЛЕН',not_found:'ТЕКСТ ЭТОЙ ПЕСНИ НЕ НАЙДЕН.',explain:'Трек может быть инструментальным, либо текст недоступен.',provide:'ДОБАВИТЬ ТЕКСТ',instrumental:'ЭТО ИНСТРУМЕНТАЛЬНЫЙ ТРЕК',retry:'ПОВТОРИТЬ',waiting:'ОЖИДАЕМ ВАШ ОТВЕТ',continue:'ПРОДОЛЖИТЬ АНАЛИЗ',back:'НАЗАД К ВАРИАНТАМ',cancel:'ОТМЕНИТЬ ПОИСК',provider:'СЕЙЧАС НЕ УДАЁТСЯ ПРОВЕРИТЬ ТЕКСТ.',insufficient:'НЕДОСТАТОЧНО ЗВУКОВЫХ ДАННЫХ ДЛЯ АНАЛИЗА.',resume:'ВОЗОБНОВЛЯЕМ АНАЛИЗ…'},
es:{paused:'ANÁLISIS EN PAUSA',not_found:'NO ENCONTRAMOS LA LETRA DE ESTA CANCIÓN.',explain:'La pista puede ser instrumental o su letra puede no estar disponible.',provide:'PROPORCIONAR LETRA',instrumental:'ESTA CANCIÓN ES INSTRUMENTAL',retry:'INTENTAR DE NUEVO',waiting:'ESPERANDO TU RESPUESTA',continue:'CONTINUAR ANÁLISIS',back:'VOLVER A LAS OPCIONES',cancel:'CANCELAR BÚSQUEDA',provider:'NO PODEMOS CONSULTAR LAS LETRAS AHORA.',insufficient:'NO HAY SUFICIENTE INFORMACIÓN SONORA PARA ANALIZAR ESTA PISTA.',resume:'REANUDANDO ANÁLISIS…'},
de:{paused:'ANALYSE PAUSIERT',not_found:'DER SONGTEXT WURDE NICHT GEFUNDEN.',explain:'Der Titel könnte instrumental sein oder der Text ist nicht verfügbar.',provide:'SONGTEXT EINGEBEN',instrumental:'DIESER SONG IST INSTRUMENTAL',retry:'ERNEUT VERSUCHEN',waiting:'WIR WARTEN AUF DEINE ANTWORT',continue:'ANALYSE FORTSETZEN',back:'ZURÜCK ZU DEN OPTIONEN',cancel:'SUCHE ABBRECHEN',provider:'DER SONGTEXT KANN GERADE NICHT GEPRÜFT WERDEN.',insufficient:'FÜR DIE ANALYSE FEHLEN AUSREICHENDE KLANGDATEN.',resume:'ANALYSE WIRD FORTGESETZT…'},
fr:{paused:'ANALYSE EN PAUSE',not_found:'NOUS N’AVONS PAS TROUVÉ LES PAROLES.',explain:'Ce titre peut être instrumental ou ses paroles indisponibles.',provide:'FOURNIR LES PAROLES',instrumental:'CE MORCEAU EST INSTRUMENTAL',retry:'RÉESSAYER',waiting:'DANS L’ATTENTE DE VOTRE RÉPONSE',continue:'POURSUIVRE L’ANALYSE',back:'RETOUR AUX OPTIONS',cancel:'ANNULER LA RECHERCHE',provider:'IMPOSSIBLE DE CONSULTER LES PAROLES MAINTENANT.',insufficient:'LES DONNÉES SONORES SONT INSUFFISANTES POUR ANALYSER CE TITRE.',resume:'REPRISE DE L’ANALYSE…'},
ja:{paused:'分析を一時停止しました',not_found:'この曲の歌詞が見つかりませんでした。',explain:'インストゥルメンタル曲か、歌詞が未登録の可能性があります。',provide:'歌詞を入力',instrumental:'この曲はインストゥルメンタルです',retry:'もう一度試す',waiting:'回答をお待ちしています',continue:'分析を続ける',back:'選択肢に戻る',cancel:'検索をキャンセル',provider:'現在、歌詞を確認できません。',insufficient:'この曲を分析するための音響情報が不足しています。',resume:'分析を再開しています…'}
});
