import {describe,expect,it,vi} from 'vitest';
import {classifyGeminiError,overallGeminiState,runGeminiHealth} from '../functions/_lib/gemini-health.js';
import worker from '../workers/pipeline/src/index';
const response=(status:number,data:any,headers:Record<string,string>={})=>new Response(typeof data==='string'?data:JSON.stringify(data),{status,headers});
const vector=()=>Array.from({length:768},(_,i)=>i/768);
describe('Gemini health diagnostics',()=>{
  it('tests generation and embedding independently without persistence',async()=>{const fetcher=vi.fn(async(url:string)=>url.includes('/models?')?response(200,{models:[{name:'models/gemini-2.5-flash',supportedGenerationMethods:['generateContent']}]}):url.includes(':generateContent')?response(200,{candidates:[{content:{parts:[{text:'{"ok":true}'}]}}]}):response(200,{embedding:{values:vector()}}));const result=await runGeminiHealth('candidate-key-long-enough',{fetcher});expect(result.generation).toMatchObject({state:'HEALTHY',model:'gemini-2.5-flash'});expect(result.embedding).toMatchObject({state:'HEALTHY',model:'gemini-embedding-2'});expect(fetcher).toHaveBeenCalledTimes(3);});
  it('reports generation limiting while embedding remains operational',async()=>{const fetcher=vi.fn(async(url:string)=>url.includes('/models?')?response(200,{models:[{name:'models/gemini-2.5-flash',supportedGenerationMethods:['generateContent']}]}):url.includes(':generateContent')?response(429,{error:{status:'RESOURCE_EXHAUSTED',message:'rate limit'}},{'Retry-After':'12'}):response(200,{embedding:{values:vector()}}));const result=await runGeminiHealth('candidate-key-long-enough',{fetcher});expect(result.generation.state).toBe('RATE_LIMITED');expect(result.embedding.state).toBe('HEALTHY');expect(overallGeminiState(result)).toBe('RATE_LIMITED');});
  it('requires daily evidence before reporting exhausted daily quota',()=>{expect(classifyGeminiError(Error('Gemini transient 429: RESOURCE_EXHAUSTED QuotaFailure requests per day')).state).toBe('QUOTA_EXHAUSTED');expect(classifyGeminiError(Error('Gemini transient 429: RESOURCE_EXHAUSTED')).state).toBe('RATE_LIMITED');});
  it.each([[401,'INVALID_CREDENTIAL'],[403,'INVALID_CREDENTIAL'],[404,'MODEL_UNAVAILABLE'],[408,'PROVIDER_UNAVAILABLE'],[500,'PROVIDER_UNAVAILABLE'],[503,'PROVIDER_UNAVAILABLE']])('classifies HTTP %i as %s',(status,state)=>expect(classifyGeminiError(Error(`Gemini ${status}: failure`)).state).toBe(state));
  it('fails only embedding when dimensions are incorrect',async()=>{const fetcher=vi.fn(async(url:string)=>url.includes('/models?')?response(200,{models:[]}):url.includes(':generateContent')?response(200,{candidates:[{content:{parts:[{text:'{"ok":true}'}]}}]}):response(200,{embedding:{values:[1,2]}}));const result=await runGeminiHealth('candidate-key-long-enough',{fetcher});expect(result.generation.state).toBe('HEALTHY');expect(result.embedding.state).not.toBe('HEALTHY');});
  it('protects worker diagnostics',async()=>{const env:any={ADMIN_TOKEN:'internal'};for(const path of ['/admin/gemini-health','/admin/gemini-validate']){const result=await worker.fetch(new Request('https://worker.test'+path,{method:'POST'}),env as any);expect(result.status).toBe(401);}});
});
