import { describe,it,expect,vi } from 'vitest';
import { GeminiClient,RetryableError } from '../functions/_lib/gemini.js';

const response=(status:number,data:any,headers:any={})=>new Response(typeof data==='string'?data:JSON.stringify(data),{status,headers:{'content-type':'application/json',...headers}});
describe('GeminiClient',()=>{
  it('discovers eligible stable generation models and ignores incompatible models',async()=>{const fetcher=vi.fn().mockResolvedValue(response(200,{models:[{name:'models/gemini-2.5-flash',supportedGenerationMethods:['generateContent']},{name:'models/gemini-tts',supportedGenerationMethods:['generateContent']},{name:'models/gemini-embedding-2',supportedGenerationMethods:['embedContent']}]}));const client=new GeminiClient('key',fetcher as any);expect((await client.listGenerativeModels())[0]).toBe('gemini-2.5-flash');expect(await client.listGenerativeModels()).not.toContain('gemini-tts');});
  it('falls back to another eligible model on a temporary model failure',async()=>{const fetcher=vi.fn().mockResolvedValueOnce(response(200,{models:[{name:'models/gemini-2.5-flash-lite',supportedGenerationMethods:['generateContent']},{name:'models/gemini-2.5-flash',supportedGenerationMethods:['generateContent']}]})).mockResolvedValueOnce(response(503,'busy')).mockResolvedValueOnce(response(503,'busy')).mockResolvedValueOnce(response(503,'busy')).mockResolvedValueOnce(response(200,{candidates:[{content:{parts:[{text:'{"ok":true}'}]}}]}));const client=new GeminiClient('key',fetcher as any);const out=await client.generateJson({system:'s',prompt:'p',schema:{type:'object'}});expect(out.data.ok).toBe(true);expect(out.model).toBe('gemini-2.5-flash');});
  it('does not silently change embedding models',async()=>{const fetcher=vi.fn().mockResolvedValue(response(503,'busy',{'Retry-After':'3600'}));const client=new GeminiClient('key',fetcher as any);await expect(client.embed('x')).rejects.toBeInstanceOf(RetryableError);expect(fetcher).toHaveBeenCalledTimes(1);});
});
