import {beforeEach,describe,expect,it,vi} from 'vitest';
import {getSpotifyTrack,mapSpotifyTrack,parseDirectedSpotifyQuery,parseSpotifyTrackInput,rerankSpotifyTracks,resetSpotifyTokenForTests,resolveSpotifyTrackUrl,searchSpotifyTracks,selectSpotifyImage} from '../functions/_lib/spotify.js';
import {resolveCanonicalSong,selectGeniusHit,selectLyricsMatch} from '../functions/_lib/song-identity.js';
import {recommendationCacheKey,RECOMMENDER_VERSION} from '../functions/_lib/recommender.js';
import {onRequestGet as musicSearch} from '../functions/music-search.js';
import {buscarCapaMusica} from '../functions/recommend.js';

const id='4uLU6hMCjMI75M1A2tKUQC';
const id2='0VjIjW4GlUZAMYd2vXMi3b';
const spotify={id,name:'Everybody Wants to Love You',artists:[{name:'Japanese Breakfast'}],album:{id:'album-id',name:'Psychopomp',release_date:'2016-04-01',images:[{url:'large.jpg',width:640,height:640},{url:'medium.jpg',width:300,height:300},{url:'small.jpg',width:64,height:64}],external_urls:{spotify:'https://open.spotify.com/album/album-id'}},duration_ms:203123,external_urls:{spotify:'https://open.spotify.com/track/'+id},uri:'spotify:track:'+id,explicit:false,external_ids:{isrc:'USSC11501980'}};
const env={SPOTIFY_CLIENT_ID:'client',SPOTIFY_CLIENT_SECRET:'secret'};
beforeEach(()=>{resetSpotifyTokenForTests();vi.restoreAllMocks()});
function spotifyFetch(){
  return vi.fn()
    .mockResolvedValueOnce(new Response(JSON.stringify({access_token:'token',expires_in:3600}),{status:200}))
    .mockResolvedValueOnce(new Response(JSON.stringify(spotify),{status:200}));
}

describe('Spotify input safety',()=>{
 it('marks exact Spotify URLs and URIs explicitly for frontend auto-confirmation',async()=>{for(const query of ['https://open.spotify.com/track/'+id,'https://open.spotify.com/intl-pt/track/'+id,'spotify:track:'+id]){vi.stubGlobal('fetch',spotifyFetch());const response=await musicSearch({request:new Request('https://site/music-search?q='+encodeURIComponent(query)),env} as any);const data:any=await response.json();expect(data.mode).toBe('exact');expect(data.items).toHaveLength(1);expect(data.items[0].provider_id).toBe(id);resetSpotifyTokenForTests();}});
 it('parses direct, localized and URI track ids while ignoring query strings',()=>{for(const value of ['https://open.spotify.com/track/'+id,'https://open.spotify.com/intl-pt/track/'+id,'https://open.spotify.com/intl-br/track/'+id+'?si=abc','https://open.spotify.com/intl-en/track/'+id+'?utm_source=x','spotify:track:'+id])expect(parseSpotifyTrackInput(value)).toMatchObject({kind:'track',id})});
 it('rejects localized non-track resources and external URLs',()=>{for(const type of ['artist','album','playlist'])expect(parseSpotifyTrackInput(`https://open.spotify.com/intl-pt/${type}/${id}`)?.kind).toBe('not_track');for(const value of ['https://open.spotify.com/episode/'+id,'https://evil.example/track/'+id,'file:///track/'+id,'http://localhost/track/'+id,'http://127.0.0.1/track/'+id])expect(parseSpotifyTrackInput(value)?.kind).toMatch(/not_track|invalid_url/)});
 it('resolves an exact URL through the track endpoint',async()=>{vi.stubGlobal('fetch',spotifyFetch());expect((await resolveSpotifyTrackUrl(env,'https://open.spotify.com/track/'+id))?.provider_id).toBe(id)});
 it('resolves spotify.link when its redirect is a localized track URL',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValueOnce(new Response(null,{status:302,headers:{location:'https://open.spotify.com/intl-pt/track/'+id+'?si=abc'}})).mockResolvedValueOnce(new Response(JSON.stringify({access_token:'token',expires_in:3600}))).mockResolvedValueOnce(new Response(JSON.stringify(spotify))));expect((await resolveSpotifyTrackUrl(env,'https://spotify.link/example'))?.provider_id).toBe(id)});
 it('maps search results without joining the artist into the title',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({access_token:'token',expires_in:3600}))).mockResolvedValueOnce(new Response(JSON.stringify({tracks:{items:[spotify]}}))));const [track]=await searchSpotifyTracks(env,'Everybody Wants to Love You Japanese Breakfast');expect(track).toMatchObject({title:'Everybody Wants to Love You',artist:'Japanese Breakfast',album:'Psychopomp'})});
 it('delivers Style by Taylor Swift for the Style taylor regression',async()=>{const style={...spotify,name:'Style',artists:[{name:'Taylor Swift'}],album:{...spotify.album,name:'1989',release_date:'2014-10-27'}};vi.stubGlobal('fetch',vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({access_token:'token',expires_in:3600}))).mockResolvedValueOnce(new Response(JSON.stringify({tracks:{items:[style]}}))));const response=await musicSearch({request:new Request('https://site/music-search?q=Style%20taylor'),env} as any),data:any=await response.json();expect(response.status).toBe(200);expect(data).toMatchObject({mode:'search',status:'results',fallback:false});expect(data.items[0]).toMatchObject({title:'Style',artist:'Taylor Swift',album:'1989'});});
 it('returns multiple choices for a title-only Style query without auto-confirming',async()=>{const other={...spotify,id:id2,name:'Style (Live)'};vi.stubGlobal('fetch',vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({access_token:'token',expires_in:3600}))).mockResolvedValueOnce(new Response(JSON.stringify({tracks:{items:[spotify,other]}}))));const response=await musicSearch({request:new Request('https://site/music-search?q=Style'),env} as any),data:any=await response.json();expect(data.mode).toBe('search');expect(data.items).toHaveLength(2);});
 it('maps safe album identity, exact artwork and canonical Spotify links',()=>expect(mapSpotifyTrack(spotify)).toMatchObject({album_id:'album-id',album_release_date:'2016-04-01',album_release_year:'2016',album_image_url:'medium.jpg',spotify_url:'https://open.spotify.com/track/'+id,spotify_uri:'spotify:track:'+id}));
 it('selects the smallest image that satisfies the target without cropping',()=>{expect(selectSpotifyImage(spotify.album.images,48)?.url).toBe('small.jpg');expect(selectSpotifyImage(spotify.album.images,200)?.url).toBe('medium.jpg');expect(selectSpotifyImage(spotify.album.images,1000)?.url).toBe('large.jpg')});
 it('runs a second filtered pass for an explicit title and artist, merges ids and reranks locally',async()=>{const wrong={...spotify,id:id2,name:'Wrong Song',artists:[{name:'Other'}]},fetchMock=vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({access_token:'token',expires_in:3600}))).mockResolvedValueOnce(new Response(JSON.stringify({tracks:{items:[wrong,spotify]}}))).mockResolvedValueOnce(new Response(JSON.stringify({tracks:{items:[spotify]}})));vi.stubGlobal('fetch',fetchMock);const tracks=await searchSpotifyTracks(env,'Everybody Wants to Love You - Japanese Breakfast',10);expect(parseDirectedSpotifyQuery('Everybody Wants to Love You — Japanese Breakfast')).toEqual({title:'Everybody Wants to Love You',artist:'Japanese Breakfast'});expect(tracks.map((x:any)=>x.provider_id)).toEqual([id,id2]);expect(fetchMock.mock.calls[2][0]).toContain('track%3A%22Everybody%20Wants%20to%20Love%20You%22%20artist%3A%22Japanese%20Breakfast%22')});
 it('ranks title-only queries without requiring an artist match',()=>{const tracks=rerankSpotifyTracks('In Heaven',[{...mapSpotifyTrack(spotify),provider_id:id2,title:'Different'}, {...mapSpotifyTrack(spotify),title:'In Heaven'}]);expect(tracks[0].title).toBe('In Heaven')});
 it('uses track and search KV hits without Spotify API calls',async()=>{const store=new Map<string,any>(),kv={get:vi.fn(async(k:string)=>store.get(k)||null),put:vi.fn(async(k:string,v:string)=>store.set(k,JSON.parse(v)))};const cached=mapSpotifyTrack(spotify);store.set(`spotify:track:${id}`,cached);const noFetch=vi.fn();vi.stubGlobal('fetch',noFetch);const cachedTrack=await getSpotifyTrack({...env,MOOVIBE_DB:kv},id);expect(cachedTrack.provider_id).toBe(id);expect(noFetch).not.toHaveBeenCalled();resetSpotifyTokenForTests();const fetchMock=vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({access_token:'token',expires_in:3600}))).mockResolvedValueOnce(new Response(JSON.stringify({tracks:{items:[spotify]}})));vi.stubGlobal('fetch',fetchMock);await searchSpotifyTracks({...env,MOOVIBE_DB:kv},'cache me');const calls=fetchMock.mock.calls.length;await searchSpotifyTracks({...env,MOOVIBE_DB:kv},'cache me');expect(fetchMock).toHaveBeenCalledTimes(calls)});
 it('continues normally when Spotify KV is unavailable',async()=>{const broken={get:async()=>{throw Error('down')},put:async()=>{throw Error('down')}};vi.stubGlobal('fetch',spotifyFetch());expect((await getSpotifyTrack({...env,MOOVIBE_DB:broken},id)).provider_id).toBe(id)});
 it('negative-caches a missing exact track briefly without caching server failures',async()=>{const store=new Map<string,any>(),kv={get:vi.fn(async(k:string)=>store.get(k)||null),put:vi.fn(async(k:string,v:string,o:any)=>store.set(k,{...JSON.parse(v),ttl:o.expirationTtl}))},fetchMock=vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({access_token:'token',expires_in:3600}))).mockResolvedValueOnce(new Response('',{status:404}));vi.stubGlobal('fetch',fetchMock);await expect(getSpotifyTrack({...env,MOOVIBE_DB:kv},id)).rejects.toThrow('SPOTIFY_TRACK_NOT_FOUND');expect(store.get(`spotify:track:${id}`)).toMatchObject({negative:true,ttl:300});const calls=fetchMock.mock.calls.length;await expect(getSpotifyTrack({...env,MOOVIBE_DB:kv},id)).rejects.toThrow('SPOTIFY_TRACK_NOT_FOUND');expect(fetchMock).toHaveBeenCalledTimes(calls)});
 it.each([429,500])('does not negative-cache transient Spotify %i search failures',async(status)=>{const kv={get:vi.fn(async()=>null),put:vi.fn()},responses=[new Response(JSON.stringify({access_token:'token',expires_in:3600})),new Response('',{status})];if(status===429)responses.push(new Response('',{status}));vi.stubGlobal('fetch',vi.fn().mockImplementation(()=>Promise.resolve(responses.shift())));vi.spyOn(globalThis,'setTimeout').mockImplementation(((callback:any)=>{callback();return 0;}) as any);await expect(searchSpotifyTracks({...env,MOOVIBE_DB:kv},`transient ${status}`)).rejects.toThrow();expect(kv.put).not.toHaveBeenCalled();});
 it('falls back to LRCLIB after Spotify failure and distinguishes empty from total failure',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({access_token:'token',expires_in:3600}))).mockResolvedValueOnce(new Response('',{status:500})).mockResolvedValueOnce(new Response(JSON.stringify([{id:42,trackName:'Style',artistName:'Taylor Swift'}]))));let response=await musicSearch({request:new Request('https://site/music-search?q=fallback%20style'),env} as any),data:any=await response.json();expect(data).toMatchObject({status:'results',fallback:true,items:[{provider:'lrclib'}]});resetSpotifyTokenForTests();vi.stubGlobal('fetch',vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({access_token:'token',expires_in:3600}))).mockResolvedValueOnce(new Response(JSON.stringify({tracks:{items:[]}}))));response=await musicSearch({request:new Request('https://site/music-search?q=nothing%20here'),env} as any);data=await response.json();expect(data).toMatchObject({status:'empty',fallback:false,items:[]});resetSpotifyTokenForTests();vi.stubGlobal('fetch',vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({access_token:'token',expires_in:3600}))).mockResolvedValueOnce(new Response('',{status:500})).mockResolvedValueOnce(new Response('',{status:503})));response=await musicSearch({request:new Request('https://site/music-search?q=providers%20down'),env} as any);data=await response.json();expect(response.status).toBe(503);expect(data.status).toBe('error');});
 it('keeps the exact Spotify artwork while existing providers look only for a preview',async()=>{vi.stubGlobal('fetch',vi.fn(async()=>new Response(JSON.stringify({results:[],data:[]}))));const result=await buscarCapaMusica('Everybody Wants to Love You','Japanese Breakfast',mapSpotifyTrack(spotify));expect(result).toMatchObject({coverUrl:'medium.jpg',coverSource:'spotify'})});
});

describe('canonical identity and lyrics',()=>{
 it('rebuilds browser metadata from provider id',async()=>{vi.stubGlobal('fetch',spotifyFetch());const result=await resolveCanonicalSong(env,{provider:'spotify',provider_id:id,title:'tampered',artist:'wrong'},'req');expect(result.track).toMatchObject({title:'Everybody Wants to Love You',artist:'Japanese Breakfast',identity_confirmed:true})});
 it('never advances ambiguous free text as title with an empty artist',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({access_token:'token',expires_in:3600}))).mockResolvedValueOnce(new Response(JSON.stringify({tracks:{items:[spotify]}}))));const result=await resolveCanonicalSong(env,{title:'Everybody Wants to Love You Japanese Breakfast',artist:''},'req');expect(result.track).toBeUndefined();expect(result.unresolved?.candidates[0]).toMatchObject({title:'Everybody Wants to Love You',artist:'Japanese Breakfast'})});
 it('resolves one to three tracks and permits mixed providers',async()=>{const second={...spotify,id:id2,name:'Second Song'};vi.stubGlobal('fetch',vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({access_token:'token',expires_in:3600}))).mockResolvedValueOnce(new Response(JSON.stringify(spotify))).mockResolvedValueOnce(new Response(JSON.stringify({id:42,trackName:'LR Song',artistName:'LR Artist',albumName:'LR Album',duration:180}))).mockResolvedValueOnce(new Response(JSON.stringify(second))));const inputs=[{provider:'spotify',provider_id:id},{provider:'lrclib',provider_id:'42'},{provider:'spotify',provider_id:id2}];const tracks=[];for(const input of inputs)tracks.push((await resolveCanonicalSong(env,input,'req')).track);expect(tracks).toHaveLength(3);expect(tracks.map(x=>x?.provider)).toEqual(['spotify','lrclib','spotify'])});
 it('falls back to LRCLIB when Spotify credentials are unavailable',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValueOnce(new Response(JSON.stringify([{id:42,trackName:'Fallback Song',artistName:'Fallback Artist'}]))));const result=await resolveCanonicalSong({}, {title:'Fallback Song',artist:''},'req');expect(result.unresolved?.candidates[0]).toMatchObject({provider:'lrclib',provider_id:'42'})});
 it('selects the second, correct LRCLIB result with lyrics',()=>{const result=selectLyricsMatch({title:'Everybody Wants to Love You',artist:'Japanese Breakfast'},[{id:1,trackName:'Everybody Wants to Love Everybody',artistName:'Outro Artista',plainLyrics:'wrong'},{id:2,trackName:'Everybody Wants to Love You',artistName:'Japanese Breakfast',plainLyrics:'right'}]);expect(result?.provider_id).toBe('2');expect(result?.plainLyrics).toBe('right')});
 it('selects a matching Genius hit rather than hits[0]',()=>{const result=selectGeniusHit({title:'Everybody Wants to Love You',artist:'Japanese Breakfast'},[{result:{id:1,title:'Wrong',primary_artist:{name:'Other'}}},{result:{id:2,title:'Everybody Wants to Love You',primary_artist:{name:'Japanese Breakfast'}}}]);expect(result?.id).toBe(2)});
 it('preserves The One regression',()=>expect(selectLyricsMatch({title:'The One',artist:'Limp Bizkit'},[{id:1,trackName:'Break Stuff',artistName:'Limp Bizkit',plainLyrics:'wrong'}])).toBeNull());
 it('versions recommendation keys around identity providers',()=>{expect(RECOMMENDER_VERSION).toBe('catalog-v5-rich-curation');expect(recommendationCacheKey([{provider:'spotify',provider_id:id,title:'x',artist:'y'}])).not.toBe(recommendationCacheKey([{provider:'lrclib',provider_id:id,title:'x',artist:'y'}]))});
});

describe('public boundary',()=>{
 it('does not expose Spotify credentials in browser files',async()=>{const fs=await import('node:fs/promises');const sources=await Promise.all(['index.html','js/script.js','js/i18n/locales.js','css/style.css'].map(file=>fs.readFile(file,'utf8')));expect(sources.join('\n')).not.toMatch(/SPOTIFY_CLIENT_(?:ID|SECRET)/)});
});
