export const adminAiScript=`(()=>{'use strict';
const app=document.querySelector('#app'),drawer=document.querySelector('#drawer'),content=document.querySelector('#drawer-content'),csrf=document.querySelector('.shell')?.dataset.csrf||'';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const copy={HEALTHY:'FUNCIONANDO',RATE_LIMITED:'AGUARDE UM POUCO',QUOTA_EXHAUSTED:'LIMITE ATINGIDO',INVALID_CREDENTIAL:'CHAVE INVÁLIDA',MODEL_UNAVAILABLE:'MODELO INDISPONÍVEL',PROVIDER_UNAVAILABLE:'SERVIÇO INDISPONÍVEL',MISCONFIGURED:'CONFIGURAÇÃO INCOMPLETA',UNKNOWN:'NÃO FOI POSSÍVEL VERIFICAR',NOT_CHECKED:'AINDA NÃO VERIFICADO'};
const advice=s=>s==='HEALTHY'?'NÃO PRECISA TROCAR.':s==='RATE_LIMITED'?'AGUARDE O LIMITE TEMPORÁRIO TERMINAR.':s==='QUOTA_EXHAUSTED'?'CONSIDERE ALTERAR A CHAVE PARA OUTRO PROJETO COM COTA DISPONÍVEL.':s==='INVALID_CREDENTIAL'?'SUBSTITUIÇÃO NECESSÁRIA.':s==='PROVIDER_UNAVAILABLE'?'VERIFIQUE NOVAMENTE. NÃO HÁ EVIDÊNCIA DE QUE A CHAVE PRECISE SER SUBSTITUÍDA.':'NÃO É POSSÍVEL DETERMINAR SE UMA TROCA É NECESSÁRIA.';
async function api(path,options={}){const r=await fetch('./api/'+path,{...options,headers:{accept:'application/json',...(options.body?{'content-type':'application/json','x-csrf-token':csrf}:{}),...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(Error(d.error||'Falha '+r.status),{data:d,status:r.status});return d;}
const op=(label,value)=>'<div class="ai-op"><span>'+label+'<small class="ai-meta">'+esc(value?.model||'—')+'</small></span><b>'+esc(copy[value?.state]||copy.NOT_CHECKED)+'</b></div>';
function card(id,no,title,subtitle,data,label){const state=data?.overall||'NOT_CHECKED';return '<article class="ai-card"><p class="kicker">'+no+' / '+esc(subtitle)+'</p><h2>'+esc(title)+'</h2><p class="ai-meta">Projeto: '+esc(label)+'</p><div class="ai-state '+state.toLowerCase()+'"><span class="ai-dot" aria-hidden="true"></span>'+esc(copy[state]||copy.UNKNOWN)+'</div>'+op(title==='CLOUDFLARE PAGES'?'GERAÇÃO DE PERFIS':'ENRIQUECIMENTO',data?.generation)+op(title==='CLOUDFLARE PAGES'?'EMBEDDING MUSICAL':'EMBEDDING DE FILMES',data?.embedding)+'<p class="ai-meta">Último teste manual: '+esc(data?.checked_at?new Date(data.checked_at).toLocaleString('pt-BR'):'nunca')+'<br>Última chamada real observada: não disponível<br>Cota restante: não disponível</p><p><b>'+esc(advice(state))+'</b></p><div class="ai-actions"><button class="archive-button" data-check>VERIFICAR AGORA</button><button class="archive-button" data-manage="'+id+'">GERENCIAR CHAVE</button></div></article>'}
function history(items=[]){if(!items.length)return '<div class="empty"><b>SEM VERIFICAÇÕES ANTERIORES</b></div>';return '<div class="table-wrap"><table><thead><tr><th>HORÁRIO</th><th>SERVIÇO</th><th>CAPACIDADE</th><th>ESTADO</th><th>MODELO</th></tr></thead><tbody>'+items.map(x=>'<tr><td>'+esc(new Date(x.checked_at).toLocaleString('pt-BR'))+'</td><td>'+esc(x.service)+'</td><td>'+esc(x.operation)+'</td><td>'+esc(copy[x.state]||copy.UNKNOWN)+'</td><td>'+esc(x.model||'—')+'</td></tr>').join('')+'</tbody></table></div>'}
async function renderAi(){if(!document.querySelector('[data-tab="ai"]')?.classList.contains('active'))return;try{const d=await api('ai');app.innerHTML='<p class="kicker">09 / GEMINI CONTROL</p><h1 class="page-title">CENTRAL<br>DE IA</h1><div class="notice"><b>MONITORAMENTO SOB DEMANDA</b><p>O polling exibe somente o último resultado armazenado. Testes manuais mínimos não garantem o sucesso de cargas longas.</p></div><div class="ai-grid">'+card('pages','01','CLOUDFLARE PAGES','RECOMENDAÇÕES',d.pages,d.project_labels.pages)+card('worker','02','PIPELINE WORKER','CATÁLOGO',d.worker,d.project_labels.worker)+'</div><section class="section"><div class="section-head"><h2>HISTÓRICO</h2><span class="section-no">ÚLTIMAS 12 OPERAÇÕES</span></div>'+history(d.history)+'</section>';bind(d);}catch(e){app.innerHTML='<div class="notice"><b>FALHA AO LER A CENTRAL DE IA</b><p>'+esc(e.message)+'</p></div>'}}
function bind(data){app.querySelectorAll('[data-check]').forEach(b=>b.addEventListener('click',async()=>{app.querySelectorAll('[data-check]').forEach(x=>x.disabled=true);try{await api('ai/check',{method:'POST',body:'{}'});await renderAi();}catch(e){alert(e.status===429?'Aguarde '+(e.data?.retry_after_seconds||60)+' segundos.':'Não foi possível verificar agora.');app.querySelectorAll('[data-check]').forEach(x=>x.disabled=false);}}));app.querySelectorAll('[data-manage]').forEach(b=>b.addEventListener('click',()=>manage(b.dataset.manage,data)));}
function manage(service,data){const command=data.manual_commands[service];content.innerHTML='<p class="kicker">GESTÃO RESTRITA</p><h2 id="drawer-title">GERENCIAR CREDENCIAL</h2><p><b>SERVIÇO:</b> '+(service==='pages'?'CLOUDFLARE PAGES':'PIPELINE WORKER')+'<br><b>SECRET:</b> GEMINI_API_KEY</p><div class="notice"><b>SUBSTITUIÇÃO AUTOMÁTICA NÃO CONFIGURADA</b><p>A chave candidata pode ser validada sem ser armazenada. A atualização permanece manual para evitar permissões administrativas amplas.</p></div><form class="secret-form" id="secret-form"><label>NOVA CHAVE GEMINI<input name="api_key" type="password" required minlength="20" maxlength="512" autocomplete="new-password"></label><label>CONFIRME A ADMIN KEY<input name="admin_key" type="password" required autocomplete="current-password"></label><button class="archive-button">TESTAR NOVA CHAVE</button></form><div id="secret-result"></div><p>Comando manual:</p><code class="command">'+esc(command)+'</code>';drawer.hidden=false;drawer.setAttribute('aria-hidden','false');content.querySelector('[name="api_key"]').focus();content.querySelector('#secret-form').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,key=form.api_key.value,admin=form.admin_key.value,result=content.querySelector('#secret-result');form.querySelector('button').disabled=true;try{const d=await api('ai/validate',{method:'POST',body:JSON.stringify({service,api_key:key,admin_key:admin})});result.innerHTML='<div class="notice"><b>'+(d.ready?'PRONTA PARA USO':'VALIDAÇÃO INCOMPLETA')+'</b>'+op('GERAÇÃO',d.generation)+op('EMBEDDING',d.embedding)+'<p>A chave não foi aplicada nem armazenada. Execute o comando manual acima somente se ambas as capacidades estiverem funcionando.</p></div>';}catch(err){result.innerHTML='<p class="error">Não foi possível validar a credencial.</p>';}finally{form.api_key.value='';form.admin_key.value='';form.querySelector('button').disabled=false;}});}
document.querySelector('[data-tab="ai"]')?.addEventListener('click',()=>setTimeout(renderAi));
const observer=new MutationObserver(()=>{if(document.querySelector('[data-tab="ai"]')?.classList.contains('active')&&!app.querySelector('.ai-grid'))setTimeout(renderAi)});observer.observe(app,{childList:true});
})();`;
