import {GeminiClient} from './gemini.js';
export const GEMINI_HEALTH_STATES=Object.freeze(['HEALTHY','RATE_LIMITED','QUOTA_EXHAUSTED','INVALID_CREDENTIAL','MODEL_UNAVAILABLE','PROVIDER_UNAVAILABLE','MISCONFIGURED','UNKNOWN','NOT_CHECKED']);
const now=()=>new Date().toISOString();
const safeMessage=value=>String(value||'').replace(/[?&]key=[^&\s]+/gi,'?key=[REDACTED]').replace(/AIza[\w-]+/g,'[REDACTED]').slice(0,240);
export function classifyGeminiError(error){const message=safeMessage(error?.message||error),lower=message.toLowerCase();const http=Number(lower.match(/(?:gemini|http|transient)\s+(400|401|403|404|408|429|500|502|503|504)/)?.[1])||null;const quota=/quota|resource_exhausted|quotafailure/i.test(message),daily=/per.?day|daily|requests.?per.?day|rpd/i.test(message);let state='UNKNOWN',summary='Não foi possível verificar.';if(/required|missing api key|misconfig/i.test(lower)){state='MISCONFIGURED';summary='Configuração incompleta.';}else if(http===401||http===403||/api key not valid|invalid credential|permission_denied/i.test(lower)){state='INVALID_CREDENTIAL';summary='Chave inválida ou sem permissão.';}else if(http===404||/model.*(?:not found|unsupported|unavailable)/i.test(lower)){state='MODEL_UNAVAILABLE';summary='Modelo indisponível.';}else if(http===429&&quota&&daily){state='QUOTA_EXHAUSTED';summary='Limite diário comprovadamente atingido.';}else if(http===429){state='RATE_LIMITED';summary=quota?'Limite atingido — tipo não determinado.':'Limite temporário observado.';}else if([408,500,502,503,504].includes(http)||/timeout|network|fetch failed|temporar/i.test(lower)){state='PROVIDER_UNAVAILABLE';summary='Serviço temporariamente indisponível.';}return {state,http_status:http,summary,error_code:state,retry_after_seconds:Number(error?.retryAfter)||null};}
const operation=async(name,model,run)=>{const started=Date.now();try{const meta=await run();return {operation:name,state:'HEALTHY',model:meta?.model||model,http_status:200,duration_ms:Date.now()-started,checked_at:now(),summary:'Operacional.'};}catch(error){return {operation:name,model,duration_ms:Date.now()-started,checked_at:now(),...classifyGeminiError(error)};}};
/** @param {string} apiKey @param {{generationLabel?:string,embeddingModel?:string,dimensions?:number,fetcher?:Function|null}} options */
export async function runGeminiHealth(apiKey,{generationLabel='dynamic',embeddingModel='gemini-embedding-2',dimensions=768,fetcher=null}={}){if(!apiKey){const base={state:'MISCONFIGURED',http_status:null,duration_ms:0,checked_at:now(),summary:'GEMINI_API_KEY não configurada.'};return {checked_at:base.checked_at,generation:{operation:'generation',model:generationLabel,...base},embedding:{operation:'embedding',model:embeddingModel,...base}};}const generation=await operation('generation',generationLabel,async()=>{const result=await new GeminiClient(apiKey,fetcher,{maxAttempts:1}).generateJson({system:'Return only the requested health object.',prompt:'Return {"ok":true}.',schema:{type:'object',properties:{ok:{type:'boolean'}},required:['ok']},temperature:0});if(result?.data?.ok!==true)throw Error('Gemini health response invalid');return {model:result.model};});const embedding=await operation('embedding',embeddingModel,async()=>{const values=await new GeminiClient(apiKey,fetcher,{maxAttempts:1}).embed('moovibe health check',{model:embeddingModel,dimensions,taskType:'RETRIEVAL_DOCUMENT'});if(values.length!==dimensions||values.some(value=>!Number.isFinite(value)))throw Error(`Invalid ${embeddingModel} embedding dimensions`);});return {checked_at:now(),generation,embedding};}
export function overallGeminiState(result){const states=[result?.generation?.state,result?.embedding?.state];if(states.every(x=>x==='HEALTHY'))return'HEALTHY';if(states.includes('INVALID_CREDENTIAL'))return'INVALID_CREDENTIAL';if(states.includes('QUOTA_EXHAUSTED'))return'QUOTA_EXHAUSTED';if(states.includes('RATE_LIMITED'))return'RATE_LIMITED';if(states.includes('MODEL_UNAVAILABLE'))return'MODEL_UNAVAILABLE';if(states.includes('MISCONFIGURED'))return'MISCONFIGURED';if(states.includes('PROVIDER_UNAVAILABLE'))return'PROVIDER_UNAVAILABLE';return'UNKNOWN';}
