import {musicTextSimilarity,scoreTrackMatch} from './music-match.js';
const TOKEN_URL='https://accounts.spotify.com/api/token',API_URL='https://api.spotify.com/v1',TRACK_ID=/^[A-Za-z0-9]{22}$/;
const TRACK_CACHE_TTL=60*60*24*7,SEARCH_CACHE_TTL=60*30,NEGATIVE_CACHE_TTL=60*5,NEGATIVE={negative:true};
let cachedAccessToken='',expiresAt=0;
export function parseSpotifyTrackInput(value){
  const raw=String(value||'').trim(),uri=raw.match(/^spotify:([^:]+):([^:]+)$/i);
  if(uri)return uri[1].toLowerCase()==='track'&&TRACK_ID.test(uri[2])?{kind:'track',id:uri[2]}:{kind:'not_track'};
  let url;try{url=new URL(raw)}catch{return null}
  const host=url.hostname.toLowerCase();
  if(url.protocol!=='https:'||!['open.spotify.com','spotify.link'].includes(host))return {kind:'invalid_url'};
  if(host==='spotify.link')return {kind:'short_url',url:url.href};
  const parts=url.pathname.split('/').filter(Boolean);
  const direct=parts.length===2&&parts[0]==='track';
  const localized=parts.length===3&&/^intl-[a-z]+(?:-[a-z]+)*$/i.test(parts[0])&&parts[1]==='track';
  const id=direct?parts[1]:localized?parts[2]:'';
  return (direct||localized)&&TRACK_ID.test(id)?{kind:'track',id}:{kind:'not_track'};
}
export function selectSpotifyImage(images,targetWidth=300){const valid=(Array.isArray(images)?images:[]).filter(image=>image?.url&&Number(image.width)>0).sort((a,b)=>Number(a.width)-Number(b.width));return valid.find(image=>Number(image.width)>=targetWidth)||valid.at(-1)||null;}
export function mapSpotifyTrack(track){const album=track?.album||{},spotifyUrl=String(track?.external_urls?.spotify||'');return {provider:'spotify',provider_id:String(track?.id||''),title:String(track?.name||''),artist:String(track?.artists?.[0]?.name||''),artists:(track?.artists||[]).map(x=>String(x.name||'')).filter(Boolean),album:String(album.name||''),album_id:String(album.id||''),album_name:String(album.name||''),album_release_date:String(album.release_date||''),album_release_year:String(album.release_date||'').slice(0,4),album_image_url:String(selectSpotifyImage(album.images,300)?.url||''),album_spotify_url:String(album.external_urls?.spotify||''),spotify_url:spotifyUrl,spotify_uri:String(track?.uri||''),explicit:Boolean(track?.explicit),duration:Number(track?.duration_ms||0)/1000,external_url:spotifyUrl,isrc:track?.external_ids?.isrc||null,lrclib_id:null};}
export async function getSpotifyAccessToken(env,force=false){if(!env?.SPOTIFY_CLIENT_ID||!env?.SPOTIFY_CLIENT_SECRET)throw Error('SPOTIFY_UNAVAILABLE');if(!force&&cachedAccessToken&&Date.now()<expiresAt-60000)return cachedAccessToken;const response=await fetch(TOKEN_URL,{method:'POST',headers:{authorization:`Basic ${btoa(`${env.SPOTIFY_CLIENT_ID}:${env.SPOTIFY_CLIENT_SECRET}`)}`,'content-type':'application/x-www-form-urlencoded'},body:'grant_type=client_credentials'});if(!response.ok)throw Error('SPOTIFY_AUTH_FAILED');const data=await response.json();cachedAccessToken=String(data.access_token||'');expiresAt=Date.now()+Number(data.expires_in||3600)*1000;if(!cachedAccessToken)throw Error('SPOTIFY_AUTH_FAILED');return cachedAccessToken;}
async function spotifyFetch(env,path,retry=true){const token=await getSpotifyAccessToken(env),response=await fetch(API_URL+path,{headers:{authorization:`Bearer ${token}`}});if(response.status===401&&retry){cachedAccessToken='';expiresAt=0;await getSpotifyAccessToken(env,true);return spotifyFetch(env,path,false)}if(response.status===429){const retryAfter=Math.min(5,Math.max(1,Number(response.headers.get('retry-after'))||1));if(retry){await new Promise(resolve=>setTimeout(resolve,retryAfter*1000));return spotifyFetch(env,path,false)}const error=Error('SPOTIFY_RATE_LIMITED');error.retryAfter=retryAfter;throw error}if(!response.ok)throw Error(response.status===404?'SPOTIFY_TRACK_NOT_FOUND':'SPOTIFY_UNAVAILABLE');return response.json();}
const cacheRead=async(env,key)=>{try{return await env.MOOVIBE_DB?.get(key,'json')??null}catch{return null}};
const cacheWrite=async(env,key,value,ttl)=>{try{await env.MOOVIBE_DB?.put(key,JSON.stringify(value),{expirationTtl:ttl})}catch{}}
const normalizedQuery=value=>String(value||'').normalize('NFKC').trim().toLocaleLowerCase().replace(/\s+/g,' ').slice(0,200);
const queryHash=value=>{let hash=0x811c9dc5;for(const char of normalizedQuery(value))hash=Math.imul(hash^char.charCodeAt(0),0x01000193);return (hash>>>0).toString(16).padStart(8,'0');};
export function parseDirectedSpotifyQuery(value){const query=String(value||'').trim();let match=query.match(/^(.+?)\s+[—–-]\s+(.+)$/);if(!match)match=query.match(/^(.+?)\s+(?:by|de)\s+(.+)$/i);if(!match)return null;const title=match[1].trim(),artist=match[2].trim();return title&&artist&&title.length<=120&&artist.length<=120?{title,artist}:null;}
const mappedItems=data=>(data?.tracks?.items||[]).map(mapSpotifyTrack).filter(track=>track.provider_id&&track.title&&track.artist);
export function rerankSpotifyTracks(query,items){const directed=parseDirectedSpotifyQuery(query);return items.map((track,index)=>{const strong=directed?scoreTrackMatch(directed,track):0;const titleOnly=musicTextSimilarity(query,track.title);const combined=musicTextSimilarity(query,`${track.title} ${track.artists.join(' ')}`);return {track,index,score:directed?strong:Math.max(titleOnly,combined*.92)};}).sort((a,b)=>b.score-a.score||a.index-b.index).map(entry=>entry.track);}
export async function searchSpotifyTracks(env,query,limit=8){const safeLimit=Math.min(10,Math.max(1,limit)),cacheKey=`spotify:search:${queryHash(query)}`,cached=await cacheRead(env,cacheKey);if(cached?.negative)return[];if(Array.isArray(cached))return cached.slice(0,safeLimit);const natural=await spotifyFetch(env,`/search?type=track&limit=10&q=${encodeURIComponent(String(query||'').slice(0,200))}`),directed=parseDirectedSpotifyQuery(query);let filtered=null;if(directed)filtered=await spotifyFetch(env,`/search?type=track&limit=10&q=${encodeURIComponent(`track:"${directed.title}" artist:"${directed.artist}"`)}`);const byId=new Map();for(const track of [...mappedItems(natural),...mappedItems(filtered)])if(!byId.has(track.provider_id))byId.set(track.provider_id,track);const ranked=rerankSpotifyTracks(query,[...byId.values()]).slice(0,10);await cacheWrite(env,cacheKey,ranked.length?ranked:NEGATIVE,ranked.length?SEARCH_CACHE_TTL:NEGATIVE_CACHE_TTL);return ranked.slice(0,safeLimit);}
export async function getSpotifyTrack(env,id){if(!TRACK_ID.test(String(id||'')))throw Error('NOT_A_TRACK');const cacheKey=`spotify:track:${id}`,cached=await cacheRead(env,cacheKey);if(cached?.negative)throw Error('SPOTIFY_TRACK_NOT_FOUND');if(cached?.provider_id)return cached;try{const track=mapSpotifyTrack(await spotifyFetch(env,`/tracks/${encodeURIComponent(id)}`));await cacheWrite(env,cacheKey,track,TRACK_CACHE_TTL);return track}catch(error){if(String(error?.message||error)==='SPOTIFY_TRACK_NOT_FOUND')await cacheWrite(env,cacheKey,NEGATIVE,NEGATIVE_CACHE_TTL);throw error}}
export async function resolveSpotifyTrackUrl(env,value){let parsed=parseSpotifyTrackInput(value);if(!parsed)return null;if(['invalid_url','not_track'].includes(parsed.kind))throw Error('NOT_A_TRACK');if(parsed.kind==='short_url'){const response=await fetch(parsed.url,{redirect:'manual'}),location=response.headers.get('location');if(!location)throw Error('NOT_A_TRACK');parsed=parseSpotifyTrackInput(new URL(location,parsed.url).href);if(!parsed||parsed.kind!=='track')throw Error('NOT_A_TRACK')}return getSpotifyTrack(env,parsed.id);}
export function resetSpotifyTokenForTests(){cachedAccessToken='';expiresAt=0;}
