import { cookieValue,createAdminSession,safeEqual,verifyAdminSession } from '../../_lib/admin-auth.js';
import { adminScript,adminStyles,dashboardMarkup,loginMarkup } from '../../_lib/admin-ui.js';

const COOKIE='moovibe_admin';
const response=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'}});
const html=(body,status=200)=>new Response(body,{status,headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store','content-security-policy':"default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; img-src https://image.tmdb.org data:; connect-src 'self'; base-uri 'none'; frame-ancestors 'none'; form-action 'self'",'x-frame-options':'DENY','referrer-policy':'no-referrer'}});
const hidden=request=>Response.redirect(new URL('/',request.url),302);
const clamp=(v,min,max,fallback)=>Math.min(max,Math.max(min,Number(v)||fallback));
const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

function page(content){return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Moovibe — Private Archive / Control Room</title><style>${adminStyles}</style></head><body>${content}</body></html>`}
function loginPage(error=false){return page(loginMarkup(error));}
function dashboard(){return page(`${dashboardMarkup()}<script>${adminScript}</script>`);}

export async function overview(db){const [movies,jobs,recs,songs]=await Promise.all([db.prepare(`SELECT COUNT(*) total,COALESCE(SUM(collection_status='complete'),0) complete,COALESCE(SUM(enrichment_status='complete'),0) enriched,COALESCE(SUM(embedding_status='complete'),0) embedded,COALESCE(SUM(date(created_at)=date('now')),0) added_today,COALESCE(SUM(created_at>=datetime('now','-7 days')),0) added_7d FROM movies`).first(),db.prepare(`SELECT COALESCE(SUM(status='queued'),0) queued,COALESCE(SUM(status='running'),0) running,COALESCE(SUM(status='done'),0) done,COALESCE(SUM(status='error'),0) errors,COALESCE(SUM(status='error' AND updated_at>=datetime('now','-1 day')),0) errors_24h,COALESCE(SUM(attempts>1),0) retries FROM pipeline_jobs`).first(),db.prepare(`SELECT COUNT(*) recommendations,COALESCE(SUM(created_at>=datetime('now','-1 day')),0) last_24h,COALESCE(SUM(success),0) successes,COALESCE(SUM(cache_hit),0) cache_hits FROM recommendation_events`).first(),db.prepare(`SELECT COUNT(*) songs,COALESCE(SUM(l.song_id IS NOT NULL),0) with_lyrics,COALESCE(SUM(p.song_id IS NOT NULL),0) with_profiles,COALESCE(SUM(p.embedding_json IS NOT NULL),0) with_embeddings FROM songs s LEFT JOIN song_lyrics l ON l.song_id=s.id LEFT JOIN song_profiles p ON p.song_id=s.id`).first()]);return {...movies,...jobs,...recs,...songs};}
async function dataApi(env,name,url){const db=env.MOOVIBE_LIBRARY,page=clamp(url.searchParams.get('page'),1,100000,1),limit=clamp(url.searchParams.get('limit'),1,100,25),offset=(page-1)*limit,q=`%${url.searchParams.get('q')||''}%`;let sql,count,bind=[];
 if(name==='catalog'){sql=`SELECT m.tmdb_id,m.title,m.original_title,m.release_year,m.original_language,m.poster_path,m.overview,m.runtime,m.vote_average,m.collection_status,m.enrichment_status,m.embedding_status,m.embedding_model,m.embedding_dimensions,m.created_at,m.updated_at,m.last_error,(SELECT GROUP_CONCAT(g.name,', ') FROM movie_genres mg JOIN genres g ON g.id=mg.genre_id WHERE mg.movie_id=m.id) genres,(SELECT GROUP_CONCAT(k.name,', ') FROM movie_keywords mk JOIN keywords k ON k.id=mk.keyword_id WHERE mk.movie_id=m.id) keywords,e.moods_json,e.themes_json,e.atmosphere_json,e.visual_style_json,e.pace,e.emotional_valence,e.energy,e.intimacy,e.surrealism,e.darkness,e.humor,e.romanticism,e.narrative_density,e.melancholy_level,e.tension_level,e.confidence FROM movies m LEFT JOIN movie_enrichments e ON e.movie_id=m.id WHERE m.title LIKE ? OR m.original_title LIKE ? OR CAST(m.tmdb_id AS TEXT)=? ORDER BY m.updated_at DESC LIMIT ? OFFSET ?`;count=`SELECT COUNT(*) n FROM movies WHERE title LIKE ? OR original_title LIKE ? OR CAST(tmdb_id AS TEXT)=?`;bind=[q,q,url.searchParams.get('q')||'',limit,offset];}
 else if(name==='pipeline'){const status=url.searchParams.get('status')||'';sql=`SELECT job_key,type,status,attempts,payload_json,available_at,started_at,completed_at,created_at,updated_at,last_error FROM pipeline_jobs WHERE (job_key LIKE ? OR type LIKE ? OR status LIKE ?) AND (?='' OR status=?) ORDER BY updated_at DESC LIMIT ? OFFSET ?`;count=`SELECT COUNT(*) n FROM pipeline_jobs WHERE (job_key LIKE ? OR type LIKE ? OR status LIKE ?) AND (?='' OR status=?)`;bind=[q,q,q,status,status,limit,offset];}
 else if(name==='recommendations'){sql=`SELECT r.request_id,r.created_at,r.language,r.songs_json,r.primary_tmdb_id,m.title primary_title,r.alternatives_json,r.candidate_count,r.semantic_count,r.numeric_count,r.union_count,r.final_count,r.keyword_fallback_count,r.duration_ms,r.cache_hit,r.success,r.error_code,r.error_message,r.top_candidates_json FROM recommendation_events r LEFT JOIN movies m ON m.tmdb_id=r.primary_tmdb_id WHERE r.request_id LIKE ? OR r.songs_json LIKE ? ORDER BY r.created_at DESC LIMIT ? OFFSET ?`;count=`SELECT COUNT(*) n FROM recommendation_events WHERE request_id LIKE ? OR songs_json LIKE ?`;bind=[q,q,limit,offset];}
 else if(name==='songs'){sql=`SELECT s.id,s.title,s.artist,s.album,s.lrclib_id,s.duration,l.source lyrics_source,l.source_reference,l.lyrics,(l.song_id IS NOT NULL) has_lyrics,p.profile_json,(p.song_id IS NOT NULL) has_profile,p.model profile_model,p.schema_version,(p.embedding_json IS NOT NULL) has_embedding,p.embedding_model,p.embedding_dimensions,s.created_at,s.updated_at FROM songs s LEFT JOIN song_lyrics l ON l.song_id=s.id LEFT JOIN song_profiles p ON p.song_id=s.id WHERE s.title LIKE ? OR s.artist LIKE ? ORDER BY s.updated_at DESC LIMIT ? OFFSET ?`;count=`SELECT COUNT(*) n FROM songs s WHERE s.title LIKE ? OR s.artist LIKE ?`;bind=[q,q,limit,offset];}
 else if(name==='system'){sql=`SELECT job_key,type,status,attempts,last_error,updated_at FROM pipeline_jobs WHERE last_error IS NOT NULL AND (job_key LIKE ? OR last_error LIKE ?) ORDER BY updated_at DESC LIMIT ? OFFSET ?`;count=`SELECT COUNT(*) n FROM pipeline_jobs WHERE last_error IS NOT NULL AND (job_key LIKE ? OR last_error LIKE ?)`;bind=[q,q,limit,offset];}
 else return response({items:[],page,total:0}); const result=await db.prepare(sql).bind(...bind).all();const total=await db.prepare(count).bind(...bind.slice(0,-2)).first();return response({items:result.results,page,limit,total:Number(total?.n)||0});}
async function traces(env,url){const limit=clamp(url.searchParams.get('limit'),1,100,25);const result=await env.MOOVIBE_LIBRARY.prepare(`SELECT request_id,created_at timestamp,'recommendation_summary' stage,language,songs_json,primary_tmdb_id,alternatives_json,candidate_count,semantic_count,numeric_count,union_count,final_count,keyword_fallback_count,duration_ms,cache_hit,success,error_code,error_message FROM recommendation_events ORDER BY created_at DESC LIMIT ?`).bind(limit).all();return response({items:result.results,available:true,temporary_detail:'Prompts e respostas completos ficam temporariamente nos Cloudflare Workers Logs. Esta lista contém somente resumos compactos permanentes do D1.'});}

export async function onRequest({request,env,params}){if(!env.ADMIN_PATH_SECRET||!safeEqual(params.secret,env.ADMIN_PATH_SECRET))return hidden(request);const base=`/admin/${params.secret}/`;const path=Array.isArray(params.path)?params.path.join('/'):String(params.path||'');
 if(request.method==='POST'&&!path){const form=await request.formData();if(!env.ADMIN_TOKEN||!safeEqual(form.get('admin_key'),env.ADMIN_TOKEN))return html(loginPage(true),401);const session=await createAdminSession(env.ADMIN_TOKEN);return new Response(null,{status:303,headers:{location:base,'set-cookie':`${COOKIE}=${session}; HttpOnly; Secure; SameSite=Strict; Path=${base}; Max-Age=43200`}});}
 const authenticated=env.ADMIN_TOKEN&&await verifyAdminSession(env.ADMIN_TOKEN,cookieValue(request,COOKIE));if(path==='logout'&&request.method==='POST')return new Response(null,{status:204,headers:{'set-cookie':`${COOKIE}=; HttpOnly; Secure; SameSite=Strict; Path=${base}; Max-Age=0`}});if(!authenticated){if(path.startsWith('api/'))return response({error:'unauthorized'},401);return html(loginPage());}
 if(!path)return html(dashboard());if(!path.startsWith('api/'))return hidden(request);if(request.method!=='GET')return response({error:'method_not_allowed'},405);const name=path.slice(4),url=new URL(request.url);if(name==='overview')return response(await overview(env.MOOVIBE_LIBRARY));if(name==='traces')return traces(env,url);if(name==='traffic')return response({available:false,reason:'Analytics Engine aceita ingestão por binding, mas consultas agregadas exigem a SQL API autenticada; nenhuma credencial é enviada ao navegador.'});return dataApi(env,name,url);
}
