import { cookieValue,createAdminSession,safeEqual,verifyAdminSession } from '../../_lib/admin-auth.js';

const COOKIE='moovibe_admin';
const response=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'}});
const html=(body,status=200)=>new Response(body,{status,headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store','content-security-policy':"default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; img-src https://image.tmdb.org data:; connect-src 'self'; base-uri 'none'; frame-ancestors 'none'; form-action 'self'",'x-frame-options':'DENY','referrer-policy':'no-referrer'}});
const hidden=request=>Response.redirect(new URL('/',request.url),302);
const clamp=(v,min,max,fallback)=>Math.min(max,Math.max(min,Number(v)||fallback));
const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

function loginPage(error=false){return `<!doctype html><html lang="pt-BR"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Moovibe Control Room</title><style>${styles}</style><body><main class="login"><div class="brand">M<span>OO</span>VIBE</div><p class="eyebrow">PRIVATE SYSTEM</p><h1>CONTROL ROOM</h1><form method="post"><label>Admin key<input name="admin_key" type="password" required autofocus autocomplete="current-password"></label>${error?'<p class="error">Não foi possível autenticar.</p>':''}<button>Entrar</button></form></main></body></html>`}
function dashboard(){return `<!doctype html><html lang="pt-BR"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Moovibe Control Room</title><style>${styles}</style><body><header><div><b>MOOVIBE</b> CONTROL ROOM <i>● ONLINE</i></div><button id="logout">SAIR</button></header><nav>${['overview','catalog','pipeline','recommendations','songs','traces','traffic','system'].map((x,i)=>`<button data-tab="${x}" class="${i?'':'active'}">${x.toUpperCase()}</button>`).join('')}</nav><main id="app"><p class="muted">Carregando…</p></main><script>${adminScript}</script></body></html>`}

const styles=`:root{color-scheme:dark;--red:#ff3b30;--ink:#090909;--panel:#151515;--line:#303030;--muted:#9b9b9b}*{box-sizing:border-box}body{margin:0;background:var(--ink);color:#f5f2ea;font:14px ui-monospace,SFMono-Regular,Consolas,monospace}header{height:72px;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;padding:0 3vw}header b,.brand{font:900 24px Arial}header b::first-letter,.brand span{color:var(--red)}header i{color:#63d17b;font-size:11px;margin-left:18px}button{background:none;color:inherit;border:1px solid var(--line);padding:11px 15px;cursor:pointer;text-transform:uppercase}button:hover,button.active{border-color:var(--red);color:var(--red)}nav{position:sticky;top:0;background:#090909eF;z-index:2;display:flex;gap:8px;padding:14px 3vw;overflow:auto}main{padding:24px 3vw 60px}.login{width:min(440px,92vw);margin:14vh auto;background:var(--panel);border:1px solid var(--line);padding:44px}.login h1{font:800 36px Arial;margin:8px 0 30px}.eyebrow,.muted{color:var(--muted)}label{display:grid;gap:10px}input,select{width:100%;background:#0d0d0d;border:1px solid var(--line);color:#fff;padding:13px;margin-bottom:14px}.login button{width:100%;background:var(--red);border-color:var(--red);color:white;font-weight:bold}.error{color:#ff746d}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:12px}.card{background:var(--panel);border:1px solid var(--line);padding:18px}.card small{color:var(--muted)}.card strong{display:block;font:700 28px Arial;margin-top:9px}table{width:100%;border-collapse:collapse;background:var(--panel);margin-top:16px}th,td{text-align:left;border-bottom:1px solid var(--line);padding:10px;vertical-align:top}th{color:var(--muted);position:sticky;top:61px;background:#151515}.toolbar{display:flex;gap:9px;flex-wrap:wrap}.toolbar input,.toolbar select{width:auto}.poster{width:38px;height:56px;object-fit:cover}.pill{border:1px solid var(--line);padding:3px 6px;font-size:11px}.detail{white-space:pre-wrap;max-width:560px;word-break:break-word}h2{font:800 28px Arial}@media(max-width:700px){header{height:58px}.login{padding:28px}th:nth-child(n+5),td:nth-child(n+5){display:none}main{padding:16px}nav{padding:10px 16px}}`;

const adminScript=`const app=document.querySelector('#app');let tab='overview';const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));async function api(q){const r=await fetch('./api/'+q);if(r.status===401){location.reload();throw Error('session')}return r.json()}const card=(k,v)=>'<div class="card"><small>'+esc(k)+'</small><strong>'+esc(v??'não disponível')+'</strong></div>';async function render(){app.innerHTML='<p class="muted">Atualizando…</p>';const d=await api(tab);if(tab==='overview'){app.innerHTML='<h2>OVERVIEW</h2><div class="cards">'+Object.entries(d).map(([k,v])=>card(k,v)).join('')+'</div>';return}if(d.available===false){app.innerHTML='<h2>'+tab.toUpperCase()+'</h2><div class="card"><strong>não disponível</strong><p class="muted">'+esc(d.reason||'Binding não configurado.')+'</p></div>';return}const rows=d.items||[];const columns=rows[0]?Object.keys(rows[0]):[];app.innerHTML='<div class="toolbar"><input id="q" placeholder="Buscar"><button id="go">FILTRAR</button></div><table><thead><tr>'+columns.map(x=>'<th>'+esc(x)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+columns.map(k=>'<td class="detail">'+esc(typeof r[k]==='object'?JSON.stringify(r[k],null,2):r[k])+'</td>').join('')+'</tr>').join('')+'</tbody></table><p class="muted">Página '+esc(d.page||1)+' · '+esc(d.total||rows.length)+' registros</p>';document.querySelector('#go').onclick=()=>renderQuery(document.querySelector('#q').value)}async function renderQuery(q){const d=await api(tab+'?q='+encodeURIComponent(q));const rows=d.items||[];app.querySelector('tbody').innerHTML=rows.map(r=>'<tr>'+Object.keys(r).map(k=>'<td class="detail">'+esc(typeof r[k]==='object'?JSON.stringify(r[k],null,2):r[k])+'</td>').join('')+'</tr>').join('')}document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelector('.active')?.classList.remove('active');b.classList.add('active');tab=b.dataset.tab;render()});document.querySelector('#logout').onclick=()=>fetch('./logout',{method:'POST'}).then(()=>location.reload());render();setInterval(render,15000);`;

async function overview(db){const [movies,jobs,recs,songs]=await Promise.all([db.prepare(`SELECT COUNT(*) total,SUM(collection_status='complete') complete,SUM(enrichment_status='complete') enriched,SUM(embedding_status='complete') embedded,SUM(date(created_at)=date('now')) added_today,SUM(created_at>=datetime('now','-7 days')) added_7d FROM movies`).first(),db.prepare(`SELECT SUM(status='queued') queued,SUM(status='running') running,SUM(status='done') done,SUM(status='error') errors FROM pipeline_jobs`).first(),db.prepare(`SELECT COUNT(*) recommendations,SUM(created_at>=datetime('now','-1 day')) last_24h,SUM(success) successes,SUM(cache_hit) cache_hits FROM recommendation_events`).first(),db.prepare(`SELECT COUNT(*) songs,SUM(l.song_id IS NOT NULL) with_lyrics,SUM(p.song_id IS NOT NULL) with_profiles,SUM(p.embedding_json IS NOT NULL) with_embeddings FROM songs s LEFT JOIN song_lyrics l ON l.song_id=s.id LEFT JOIN song_profiles p ON p.song_id=s.id`).first()]);return {...movies,...jobs,...recs,...songs};}
async function dataApi(env,name,url){const db=env.MOOVIBE_LIBRARY,page=clamp(url.searchParams.get('page'),1,100000,1),limit=clamp(url.searchParams.get('limit'),1,100,25),offset=(page-1)*limit,q=`%${url.searchParams.get('q')||''}%`;let sql,count,bind=[];
 if(name==='catalog'){sql=`SELECT tmdb_id,title,original_title,release_year,original_language,collection_status,enrichment_status,embedding_status,created_at,last_error FROM movies WHERE title LIKE ? OR original_title LIKE ? OR CAST(tmdb_id AS TEXT)=? ORDER BY created_at DESC LIMIT ? OFFSET ?`;count=`SELECT COUNT(*) n FROM movies WHERE title LIKE ? OR original_title LIKE ? OR CAST(tmdb_id AS TEXT)=?`;bind=[q,q,url.searchParams.get('q')||'',limit,offset];}
 else if(name==='pipeline'){sql=`SELECT job_key,type,status,attempts,available_at,started_at,completed_at,updated_at,last_error FROM pipeline_jobs WHERE job_key LIKE ? OR type LIKE ? OR status LIKE ? ORDER BY updated_at DESC LIMIT ? OFFSET ?`;count=`SELECT COUNT(*) n FROM pipeline_jobs WHERE job_key LIKE ? OR type LIKE ? OR status LIKE ?`;bind=[q,q,q,limit,offset];}
 else if(name==='recommendations'){sql=`SELECT request_id,created_at,language,songs_json,primary_tmdb_id,semantic_count,numeric_count,union_count,final_count,duration_ms,cache_hit,success,error_code FROM recommendation_events WHERE request_id LIKE ? OR songs_json LIKE ? ORDER BY created_at DESC LIMIT ? OFFSET ?`;count=`SELECT COUNT(*) n FROM recommendation_events WHERE request_id LIKE ? OR songs_json LIKE ?`;bind=[q,q,limit,offset];}
 else if(name==='songs'){sql=`SELECT s.id,s.title,s.artist,s.album,s.lrclib_id,l.source,p.schema_version,p.embedding_model,p.embedding_dimensions,s.created_at,s.updated_at FROM songs s LEFT JOIN song_lyrics l ON l.song_id=s.id LEFT JOIN song_profiles p ON p.song_id=s.id WHERE s.title LIKE ? OR s.artist LIKE ? ORDER BY s.updated_at DESC LIMIT ? OFFSET ?`;count=`SELECT COUNT(*) n FROM songs s WHERE s.title LIKE ? OR s.artist LIKE ?`;bind=[q,q,limit,offset];}
 else if(name==='system'){sql=`SELECT job_key,type,status,attempts,last_error,updated_at FROM pipeline_jobs WHERE last_error IS NOT NULL AND (job_key LIKE ? OR last_error LIKE ?) ORDER BY updated_at DESC LIMIT ? OFFSET ?`;count=`SELECT COUNT(*) n FROM pipeline_jobs WHERE last_error IS NOT NULL AND (job_key LIKE ? OR last_error LIKE ?)`;bind=[q,q,limit,offset];}
 else return response({items:[],page,total:0}); const result=await db.prepare(sql).bind(...bind).all();const total=await db.prepare(count).bind(...bind.slice(0,-2)).first();return response({items:result.results,page,limit,total:total?.n||0});}
async function traces(env,url){if(!env.AI_AUDIT_LOGS)return response({items:[],available:false});const listed=await env.AI_AUDIT_LOGS.list({limit:clamp(url.searchParams.get('limit'),1,100,25)});const items=[];for(const object of listed.objects){const stored=await env.AI_AUDIT_LOGS.get(object.key);if(stored)items.push(await stored.json());}return response({items,available:true});}

export async function onRequest({request,env,params}){if(!env.ADMIN_PATH_SECRET||!safeEqual(params.secret,env.ADMIN_PATH_SECRET))return hidden(request);const base=`/admin/${params.secret}/`;const path=Array.isArray(params.path)?params.path.join('/'):String(params.path||'');
 if(request.method==='POST'&&!path){const form=await request.formData();if(!env.ADMIN_TOKEN||!safeEqual(form.get('admin_key'),env.ADMIN_TOKEN))return html(loginPage(true),401);const session=await createAdminSession(env.ADMIN_TOKEN);return new Response(null,{status:303,headers:{location:base,'set-cookie':`${COOKIE}=${session}; HttpOnly; Secure; SameSite=Strict; Path=${base}; Max-Age=43200`}});}
 const authenticated=env.ADMIN_TOKEN&&await verifyAdminSession(env.ADMIN_TOKEN,cookieValue(request,COOKIE));if(path==='logout'&&request.method==='POST')return new Response(null,{status:204,headers:{'set-cookie':`${COOKIE}=; HttpOnly; Secure; SameSite=Strict; Path=${base}; Max-Age=0`}});if(!authenticated){if(path.startsWith('api/'))return response({error:'unauthorized'},401);return html(loginPage());}
 if(!path)return html(dashboard());if(!path.startsWith('api/'))return hidden(request);if(request.method!=='GET')return response({error:'method_not_allowed'},405);const name=path.slice(4),url=new URL(request.url);if(name==='overview')return response(await overview(env.MOOVIBE_LIBRARY));if(name==='traces')return traces(env,url);if(name==='traffic')return response({available:false,reason:'Analytics Engine aceita ingestão por binding, mas consultas agregadas exigem a SQL API autenticada; nenhuma credencial é enviada ao navegador.'});return dataApi(env,name,url);
}
